course_name = "创新训练课 B"
repo_type = "normal"
course_code = "AUTO2003B"

# 网络资源（电子书、网课等）
[[online_resources]]
title = "MaxwellJay256/MetroTicketingSystem"
url = "https://github.com/MaxwellJay256/MetroTicketingSystem"
description = "模拟地铁售票系统，有二进制成品和 demo。"

[[online_resources]]
title = "chenxijun/KingdomCard"
url = "https://github.com/chenxijun/KingdomCard"
description = "三国杀游戏。C/S 架构，支持局域网联机。前端 Qt6，后端 Modern C++。"

[[online_resources]]
title = "Simulate_Shenzhen_Subway_Ticketing_System"
url = "https://github.com/novemberinnorth/Simulate_Shenzhen_Subway_Ticketing_System"
description = "使用 C++ Qt6 实现图形化的模拟深圳地铁自动售票系统。"

[[online_resources]]
title = "Sieroy/Musnake"
url = "https://github.com/Sieroy/Musnake"
description = "使用 SDL2 实现图形界面的、融合轻量音游玩法的贪吃蛇游戏。附有可玩 demo。"

# 核心课程评价区块
[[course]]
content = """
课程设计是在学生完成高级语言程序设计课程学习后进行的。
翻译：**自己动手制作一个程序**。

选题从课程给出的几个中选择一个，或者提交你自己的选题。
2022 级给出的选题有：
- 学院职工管理信息管理系统
- 学院学生信息管理系统
- 模拟地铁自动售票系统
- 贪吃蛇小游戏
- 跳棋游戏
- 简易三国杀游戏
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """
这应该是自动化学生为数不多的参与软件开发的机会。

选题
图省事的话推荐贪吃蛇之类的小游戏，借助 AI 不到 1 天就能速通，但是你需要想想答辩的时候能说些什么。
如果想多积累一点敲代码经验，可以选择客户端类型的软件（信息管理系统、售票系统），体验一下前、后端的开发思想。

组队
课程要求 1-2 人一个小组。如果选择组队，建议启用 git 这种版本控制系统。
如果对团队协作没有信心，或者对你的队友没有信心，一个人组队会轻松很多。

挑选一个开发框架
**课程要求项目必须使用 `C/C++`**，需要使用第三方库来实现 GUI。
1. **EasyX**：基于 `GDI+`，古老简单但功能有限。
2. **Qt**：跨平台的 GUI 开发框架，功能强大，学生证可以申请教育许可证（个人推荐）。
3. **MFC**：Windows 编程框架，兼容性好但开发效率低。
4. **C#**：仅限在实现图形界面的时候使用，代码逻辑仍需使用 `C/C++`。

IDE
推荐使用 **Visual Studio**（MFC 或 C# 的最佳选择，也有 Qt 插件）或 **Qt Creator**。
"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2023-12-01" }
