course_name = "系统建模与仿真"
repo_type = "normal"
course_code = "AUTO3004"

# 授课教师 (Lecturers)
[[lecturers]]
name = "李衍杰"

  [[lecturers.reviews]]
  content = """
  授课风格：轻松愉快，稍显啰嗦，实验课会带领大家写代码并亲自检查，偶尔点名。
              是否需要认真听讲做笔记：正常听课，考前复习。
              听课建议：注意重点强调的最小二乘，PPT 标红简答，龙格库塔法计算。
  """
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "李芃"

  [[lecturers.reviews]]
  content = """
  授课风格：念 ppt。
              听课建议：正常听课，考前复习。
  """
  author = { name = "", link = "", date = "" }

# 核心课程评价区块
[[course]]
content = """课程内容可以分为三个部分：① 纯科普 ② 告诉你在以后遇到问题了可以用某个方法，但是因为复杂等原因不方便考 ③ 剩下才是能考试的核心内容。不要因为有的内容听不懂就灰心甚至摆烂。
"""
author = { name = "phychi", link = "https://github.com/phychi", date = "2023-11-01" }

[[exam]]
content = """可以用于考试的知识密度并不大，很多计算量很大的内容在平时的编程中实现过了，所以不会考。而且由于你校众所周知的阉割传统，很多容易的内容被不断重复，难的内容都会被砍掉。
"""
author = { name = "OliverWu515", link = "https://github.com/OliverWu515", date = "2023-11-01" }

[[exam]]
content = """考试难度：背诵+简单计算，龙格库塔法可能步骤多一些。"""
author = { name = "不知名学长", link = "", date = "2022-11-01" }

[[exam]]
content = """
24 年秋，考试整体难度非常简单，把往年题背熟即可。事实上，对自控理论 A 这门课略懂一二就可以在建模与仿真的考试上拿下大部分题目。
最后一节课的后半程会讲哪些内容不考，可以总结为看起来就考不了的知识点不考。
24 年秋，考试可以带计算器。
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-11-01" }
