course_name = "æœºç”µç³»ç»Ÿæ§åˆ¶åŸºç¡€"
repo_type = "normal"
course_code = "MECH3005"

# æˆè¯¾æ•™å¸ˆ (Lecturers)
[[lecturers]]
name = "åŒ…æ–Œ"
[[lecturers]]
name = "ç‹æ˜•"

# ç½‘ç»œèµ„æºï¼ˆç”µå­ä¹¦ã€ç½‘è¯¾ç­‰ï¼‰
[[online_resources]]
title = "Nyquist åˆ¤æ®æ›´å¸¸ç”¨çš„æ–¹æ³• (Bilibili)"
url = "https://www.bilibili.com/video/BV1ikWneMEhc/"
description = "è¯¾æœ¬ä»‹ç»çš„ Nyquist åˆ¤æ®æ–¹æ³•ä¸æ˜¯å¾ˆå¥½ç”¨ï¼Œæ¨èå‚è€ƒæ­¤è§†é¢‘ã€‚"

[[exam]]
content = """2025 ç§‹è€ƒè¯•ä¸ç®—å¾ˆéš¾ï¼Œæ€»åˆ†å¹³å‡åˆ†ä¼°è®¡æœ‰ 90 åˆ†ã€‚"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01-01" }

[[advice]]
content = """
æŒ‰ç™¾åˆ†åˆ¶çš„å¹³æ—¶åˆ†é‡Œæœ‰ 20 åˆ†é€‰åšé¢˜ï¼šå†™ä¸€ç¯‡å°è®ºæ–‡ï¼›è¯¾ä¸Šæ²¡è¯´æ¸…æ¥šæ˜¯å¦æ˜¯é€‰åšé¢å¤–åŠ åˆ†ï¼ˆ100+20=120ï¼‰ã€ä½œä¸šè¯´æ˜é‡Œä¹Ÿæ²¡æœ‰è¯´ï¼Œä½†å°±æœ€åæˆç»©æ¥çœ‹æ˜¯ä¸åš 100-20â€”â€”å¹¶éã€Œé€‰åšé¢˜ã€ğŸ¤£

è¯¾æœ¬ä»‹ç»çš„ Nyquist åˆ¤æ®æ–¹æ³•ä¸æ˜¯å¾ˆå¥½ç”¨ï¼Œå­¦æœ‰ä½™åŠ›~~æˆ–è€…æ ¹æœ¬æ²¡å­¦~~çš„åŒå­¦å¯ä»¥å‚è€ƒè‡ªåŠ¨åŒ–[æ›´å¸¸ç”¨çš„æ–¹æ³•](https://www.bilibili.com/video/BV1ikWneMEhc/)ã€‚
"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01-01" }
