course_name = "日语I"
repo_type = "normal"
course_code = "WOCD1008"

# 授课教师 (Lecturers)
[[lecturers]]
name = "刘玥扬"

  [[lecturers.reviews]]
  content = """
  授课风格：非常好的老师，上课经常会带小零食，讲一段时间的课后会给同学们听歌放视频放松，偶尔还会有成绩 bonus 哦（
              听课建议：放松就好啦，这门课不像那些必修一样卷死卷活，大家都是抱着愉悦的心情来听课的
              如果你真的对日语很感兴趣的话只靠课上内容（五十音 + 一些基础语法）是远远不够的
  """
  author = { name = "longlin", link = "", date = "2024-07-01" }

[[exam]]
content = """24春季无作业也无考试"""
author = { name = "longlin", link = "", date = "2024-07-01" }

[[advice]]
content = """
我自己的日语也才处于刚入门的阶段，平时看番剧看得多可能语感听力会好一点，会些简单短语（

目的是为日常生活交流的话可以在 Duolingo 这款 App 上学习，我是将语言调整成了英文，用英文学日语，效果还不错，缺点是汉字太少以及语法不系统；
以 JLPT 散步为目的的话大概更偏向于《标日》《大家的日语》这些语法书（我自己一次都没考过所以不是很清楚
"""
author = { name = "longlin", link = "", date = "2024-07-01" }
