course_name = "系统辨识"
repo_type = "normal"
course_code = "AUTO5002"

[[lecturers]]
name = "吴爱国"

  [[lecturers.reviews]]
  content = "授课风格：见[自动控制理论B](https://hoa.moe/docs/junior-spring/auto3001b/)课程页面。"
  author = { name = "", link = "", date = "" }

  [[lecturers.reviews]]
  content = "对于这门课程，纯板书，不用 PPT；并且不戴麦（2024 年情况），所以回放无声，需要到线下去听讲。"
  author = { name = "", link = "", date = "2024-01-01" }

[[course]]
content = "讲义放在校内网盘供大家下载。"
author = { name = "", link = "", date = "" }