course_name = "凸优化与最优控制"
repo_type = "normal"
course_code = "AUTO5023"

# 全局注意事项/简介
notices = """
课程内容用于讲解凸优化的课时占了约四分之三，最优控制约占四分之一。
"""

# 成绩评定
[[lecturers]]
name = "李衍杰"
  [[lecturers.reviews]]
  content = """
  课堂轻松愉悦，时常插入一些有趣的题外话。讲课节奏不快（甚至略显拖沓），有时会在一些具体示例上花很长时间讲解。不太点名。
  听课建议：可以重点听听优化问题之间的转化。
  课内知识我跳帧听讲，课外唠嗑我逐字分享。
  """
  author = { name = "Hye", link = "https://github.com/Co-ding-Man", date = "2025-01-01" }

# 教材与参考书
[[textbooks]]
title = "Convex Optimization"
book_author = "Stephen Boyd / Lieven Vandenberghe"
publisher = "Cambridge University Press"
edition = ""
type = "textbook"

[[textbooks]]
title = "Applied Optimal Control"
book_author = "A. E. Bryson / Y. C. Ho"
publisher = "Taylor & Francis"
edition = "1975"
type = "reference"

[[textbooks]]
title = "Optimal Control Theory an Introduction"
book_author = "D. E. Kirk"
publisher = "Dover Publication Inc."
edition = "2004"
type = "reference"

[[textbooks]]
title = "Dynamic Programming and Optimal Control"
book_author = "D. P. Bertsekas"
publisher = "Athena Scientific"
edition = "2007"
type = "reference"

# 电子书资源
[[online_resources]]
title = "Convex Optimization 教材官网"
url = "https://web.stanford.edu/~boyd/cvxbook/"
description = "可下载配套课件"
author = { name = "", link = "", date = "" }

# 核心课程评价区块
[[course]]
content = """
**第一讲 绪论**：主要内容是：凸优化与最优控制简介，包括各种凸优化和最优控制应用的实例。

**第二讲 凸集**：主要内容是：凸集的定义和例子，**证明某集合是凸集的方法（重点）**，保持集合凸性的运算，广义不等式。

**第三讲 凸函数**：主要内容是：凸函数的定义和例子，**证明某函数是凸函数的方法（重点）**，保持函数凸性的运算，共轭函数，准凸函数，对数凹函数和对数凸函数，关于广义不等式的凸性。

**第四讲 凸优化问题**：主要内容是：凸优化问题及其特殊实例，如线性规划、二次规划、二阶锥规划和半定规划等；**各种优化问题之间的转化（重点）**，例如将非凸优化问题转化为凸优化问题，将非线性规划问题转化为线性规划问题等。

**第五讲 对偶理论**：主要内容是：拉格朗日对偶理论，对偶优化问题及其几何解释，KKT条件。**这一讲都挺重要的，需要掌握其中的概念及推导。**

**第六讲 无约束和等式约束**：主要内容是：梯度方法、最速下降法和**牛顿法（重点）**，几乎不讨论收敛性分析。补充介绍了 Gauss-Newton 法。此外，还走马观花地讲了讲数值线性代数的知识，其中包括 Cholesky 分解、QR 分解、奇异值分解等常用的矩阵分解以及算法复杂度等。

**第七讲 内点法**：主要内容是：不等式约束优化问题的对数障碍函数方法（即“内点法”），关于内点法的收敛性只给出了多种解释而不讨论严格的收敛性分析。此外，简单提及了广义不等式约束优化问题和主对偶内点优化算法。

**第八、九讲 动态优化与最优控制（重点）**：主要内容是：动态优化问题（最优控制问题）的三大方法——变分法、庞德里亚金最大值原理和动态规划，以及最优控制的数值解法。
"""
author = { name = "Hye", link = "https://github.com/Co-ding-Man", date = "2025-01-01" }

[[exam]]
content = """
允许携带一张A4纸。可以带计算器（但基本用不上）。

这门考试的考点其实是很明确的，因为所讲的内容确实不多。凸优化中的复杂证明在课上就不会讲到，而是被当作“对我们没有什么用处”的“纯粹的数学”一笔带过（笑）。而最优控制问题中的复杂计算又难以考查。考试中最难的也就是一些稍微需要技巧的证明（主要是优化问题之间的转化），如果之前没有了解具体方法未必能想出证法，不过好在这些在课上都会讲到。
"""
author = { name = "Hye", link = "https://github.com/Co-ding-Man", date = "2025-01-01" }