course_name = "éçº¿æ€§ä¸è‡ªé€‚åº”æ§åˆ¶"
repo_type = "normal"
course_code = "AUTO5005"

notices = """
æœ¬è¯¾ç¨‹ä»¥è®²ä¹‰ä¸ºä¸»ã€‚
å¯è§æ ¡å†…ç½‘ç›˜ Lec1ï¼ˆIntroductionï¼‰ã€‚
ä¸»è¦å†…å®¹ç« èŠ‚è¯·è®¤çœŸé˜…è¯»ï¼Œå¾€å¹´æ›¾ä½œä¸ºè€ƒé¢˜å‡ºç°ã€‚
"""

[[lecturers]]
name = "æ¢…æ°"

  [[lecturers.reviews]]
  content = """
  ä¸Šè¯¾ä½¿ç”¨ iPad æ‰‹å†™æŠ•å±ï¼ŒèŠ‚å¥é£å¿«ã€‚
  è¯¾åä¼šæ›´æ–°æœ¬å¹´åº¦çš„æ‰‹å†™è®²ä¹‰ï¼Œä½†å¹¶ä¸åŠæ—¶ã€‚å»ºè®®åŒå­¦ä»¬çœ‹å¾€å¹´è®²ä¹‰é¢„ä¹ ã€‚
  å¶å°”ä»¥æé—®æ–¹å¼ç‚¹åã€‚
  """
  author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-01-01" }

[[textbooks]]
title = "Applied Nonlinear Control"
book_author = "J-J E. Slotine and Weiping Li"
publisher = "æœºæ¢°å·¥ä¸šå‡ºç‰ˆç¤¾"
edition = "English Edition"
type = "reference"

[[textbooks]]
title = "Nonlinear Systems"
book_author = "Hassan K. Khalil"
publisher = "ç”µå­å·¥ä¸šå‡ºç‰ˆç¤¾"
edition = "Third Edition"
type = "reference"

[[textbooks]]
title = "Robust and Adaptive Control with Aerospace Applications"
book_author = "E. Lavertsky and K. Wise"
publisher = "Springer-Verlag"
edition = "2013"
type = "reference"

[[textbooks]]
title = "Adaptive Control"
book_author = "K.J. Ã…strÃ¶m and B. Wittenmark"
publisher = "Dover Publications, INC."
edition = "Second Edition"
type = "reference"

[[textbooks]]
title = "Nonlinear and Adaptive Control Design"
book_author = "M. Krstic, I. Kanellakopoulos, and P. Kokotovic"
publisher = "John Wiley and Sons"
edition = "1995"
type = "reference"

[[textbooks]]
title = "Adaptive Control Tutorial"
book_author = "P. Ioannou and B. Fidan"
publisher = "SIAM Press"
edition = "2006"
type = "reference"

[[textbooks]]
title = "Nonlinear Systems: Analysis, Stability, and Control"
book_author = "Shankar Sastry"
publisher = "ä¸–ç•Œå›¾ä¹¦å‡ºç‰ˆç¤¾"
edition = "1999"
type = "reference"

[[textbooks]]
title = "Stable Adaptive Systems"
book_author = "K. Narendra and A. Annaswamy"
publisher = "Dover Publications, INC."
edition = "2005"
type = "reference"

[[online_resources]]
title = "Oliver Wu & Hye'sã€Šéçº¿æ€§ä¸è‡ªé€‚åº”æ§åˆ¶ã€‹ç¬”è®°"
url = "https://oliverwu.top/nac.html"
description = "è¯¾ç¨‹å‚è€ƒç¬”è®°"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-01-01" }

[[course]]
content = """
ä¸»è¦å†…å®¹å¦‚ä¸‹ï¼ˆè®¤çœŸçœ‹è¿™ä¸€èŠ‚ï¼Œè¿™å¯æ˜¯ä¸€é“è€ƒé¢˜ï¼‰ï¼š

1. **ç¬¬ä¸€ã€äºŒè®² ç»ªè®º**ï¼šéçº¿æ€§æ§åˆ¶ç³»ç»Ÿæ¦‚è¿°(ä»€ä¹ˆæ˜¯éçº¿æ€§ç³»ç»Ÿä¸è‡ªé€‚åº”æ§åˆ¶ã€ä¸ºä»€ä¹ˆè¦ç ”ç©¶å®ƒä»¬)ã€éçº¿æ€§æ§åˆ¶ç³»ç»Ÿçš„å»ºæ¨¡ã€éçº¿æ€§å¸¸å¾®åˆ†æ–¹ç¨‹çš„è§£ï¼ˆå­˜åœ¨ã€å”¯ä¸€æ€§ï¼Œä¸»è¦æ˜¯ Lipschitz æ¡ä»¶ï¼‰ã€‚è¿™ä¸¤è®²ä»¥äº†è§£ä¸ºä¸»ã€‚
2. **ç¬¬ä¸‰è®² è‡ªæ²»ç³»ç»Ÿçš„ç¨³å®šæ€§åˆ†æ**ï¼šè‡ªæ²»ç³»ç»Ÿ Lyapunov ç¨³å®šæ€§çš„æ¦‚å¿µï¼ˆç¨³å®šæ€§ã€æ¸è¿‘ç¨³å®šã€å…¨å±€æ¸è¿‘ç¨³å®šã€æŒ‡æ•°ç¨³å®šï¼‰ã€æ­£å®šå‡½æ•°ã€è‡ªæ²»ç³»ç»Ÿçš„ Lyapunov ç¨³å®šæ€§å®šç†ã€LaSalle ä¸å˜é›†åŸç†ï¼ˆåˆ†æåŸç‚¹ä¸æé™ç¯çš„ç¨³å®šæ€§ï¼‰ã€çº¿æ€§ç³»ç»Ÿä¸çº¿æ€§åŒ–ï¼ˆåˆ©ç”¨å±€éƒ¨çº¿æ€§åŒ–ç³»ç»Ÿçš„ Jacobianï¼‰ã€‚
3. **ç¬¬å››è®² éè‡ªæ²»ç³»ç»Ÿçš„ç¨³å®šæ€§åˆ†æ**ï¼šæ¯”è¾ƒå‡½æ•°ã€éè‡ªæ²»ç³»ç»Ÿç¨³å®šæ€§çš„æ¦‚å¿µï¼ˆé™¤äº†ä¸Šè¿°ç¨³å®šæ€§ä¹‹å¤–ï¼Œç‰¹åˆ«æ³¨æ„æ–°å¼•å…¥çš„ä¸€è‡´ç¨³å®šï¼‰ã€æ—¶å˜æ­£å®šå‡½æ•°ä¸éè‡ªæ²»ç³»ç»Ÿç¨³å®šæ€§å®šç†ï¼ˆæ³¨æ„æ—¶å˜å‡½æ•°æ­£å®šæ€§çš„åˆ¤åˆ«ï¼‰ã€çº¿æ€§æ—¶å˜ç³»ç»Ÿï¼ˆäº†è§£ä¸ºä¸»ï¼‰ ã€Barbalat å¼•ç†åŠå…¶æ¨è®ºï¼ˆé‡ç‚¹ï¼Œéœ€æŒæ¡è¯æ˜ï¼‰ã€æœ‰ç•Œæ€§å’Œæœ€ç»ˆæœ‰ç•Œæ€§ã€è¾“å…¥-çŠ¶æ€ç¨³å®šæ€§ã€‚
4. **ç¬¬äº”è®² è‡ªé€‚åº”æ§åˆ¶**ï¼šè‡ªé€‚åº”æ§åˆ¶çš„æ¦‚å¿µä¸ç±»å‹ï¼ˆç®€ç­”é¢˜è€ƒæŸ¥ï¼‰ã€å„ç§å„æ ·çš„æ¨¡å‹å‚è€ƒè‡ªé€‚åº”æ§åˆ¶ï¼ˆçº¿æ€§æ ‡é‡ç³»ç»Ÿ[ç›´æ¥å‹ã€é—´æ¥å‹]ã€å…·æœ‰éçº¿æ€§é¡¹çš„æ ‡é‡ç³»ç»Ÿã€å¤šè¾“å…¥å¤šè¾“å‡ºï¼ˆMIMOï¼‰ç³»ç»Ÿï¼‰ã€æ— å‚è€ƒæ¨¡å‹çš„è‡ªé€‚åº”æ§åˆ¶è®¾è®¡ã€é²æ£’è‡ªé€‚åº”æ§åˆ¶ï¼ˆæ­»åŒºä¿®æ­£ã€ğœ-ä¿®æ­£ã€Î±-ä¿®æ­£ã€è‡ªé€‚åº” ğœ-ä¿®æ­£ï¼Œéœ€è¦ä¼šæ¨å¹¿è‡³å¤šè¾“å…¥å¤šè¾“å‡ºï¼ˆMIMOï¼‰ç³»ç»Ÿä¸æ—¶å˜å‚æ•°æƒ…å½¢ï¼‰ã€é¢„è®¾æ€§èƒ½æ§åˆ¶ï¼ˆ2024 æ–°åŠ å…¥ï¼‰ã€‚
5. **ç¬¬å…­è®² éçº¿æ€§æ§åˆ¶ç³»ç»Ÿè®¾è®¡**ï¼šåé¦ˆæ§åˆ¶é—®é¢˜çš„ç±»åˆ«ï¼ˆçŠ¶æ€åé¦ˆé•‡å®šé—®é¢˜ã€è¾“å‡ºåé¦ˆé•‡å®šé—®é¢˜ã€è·Ÿè¸ªé—®é¢˜ï¼‰ã€åé¦ˆçº¿æ€§åŒ–ã€å„ç§å„æ ·çš„æ»‘æ¨¡æ§åˆ¶ï¼ˆé•‡å®šé—®é¢˜ã€è·Ÿè¸ªé—®é¢˜ã€æœ‰ä¸ç¡®å®šæ€§çš„è·Ÿè¸ªé—®é¢˜ã€æœ‰å¤–éƒ¨å¹²æ‰°ï¼‰ã€åæ­¥æ³•ï¼ˆåŸºæœ¬å½¢å¼ã€è‡ªé€‚åº”åæ­¥æ³•åŠå‡å°‘è¿‡å‚æ•°åŒ–ã€æœ‰è°ƒèŠ‚å‡½æ•°ï¼ˆtuning functionï¼‰çš„è‡ªé€‚åº”åæ­¥æ³•ï¼‰ã€‚
6. **ç¬¬ä¸ƒè®² å®ä¾‹ï¼šæœºæ¢°è‡‚æ§åˆ¶**ï¼šå°†å‰é¢è®²è§£è¿‡çš„æ–¹æ³•åº”ç”¨åˆ°æœºæ¢°è‡‚çš„æ§åˆ¶ä¸Šï¼ŒåŒ…æ‹¬åŸºäº Lyapunov åˆ†æçš„ä½ç½®æ§åˆ¶ï¼ˆä¸»è¦ä¾é åé¦ˆçº¿æ€§åŒ–ï¼‰ ã€è·Ÿè¸ªæ§åˆ¶ï¼ˆä½¿ç”¨æ»‘æ¨¡æ§åˆ¶ã€è‡ªé€‚åº”æ»‘æ¨¡æ§åˆ¶ã€åæ­¥æ³•æ»‘æ¨¡æ§åˆ¶ä¸é¢„è®¾æ€§èƒ½æ§åˆ¶ï¼‰ã€‚
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-01-01" }

[[exam]]
content = """
æœŸæœ«è€ƒè¯•ä¸ºé—­å·ã€ä¸å…è®¸æºå¸¦è®¡ç®—å™¨ï¼ˆclosed-book, closed-note, closed-calculator examï¼‰ã€‚å®é™…ä¸Šä¹Ÿç”¨ä¸åˆ°è®¡ç®—å™¨ã€‚
é¢˜é‡å¾ˆå¤§ï¼Œä¸è¿‡åŸºæœ¬ä¸Šæ˜¯ä¸Šè¯¾è®²è¿‡çš„ä¾‹å­æˆ–è€…æé—®çš„å˜ç§ï¼ˆè®²ä¹‰ä¸Šæ ‡æœ‰ Q å­—æ ·ä¸”ä¸ç»™å‡ºæ˜ç¡®è§£ç­”çš„é—®é¢˜ï¼‰ã€‚
ç»™åˆ†éå¸¸å®½æ¾ï¼ˆ2024 å¹´ï¼Œ98 åˆ†æ’å 7/53ï¼‰ï¼Œå¤§å®¶å³ä½¿ä¸å¤ªç¬ƒå®šä¹Ÿè¦æŠŠå¤§è‡´æ€è·¯å†™ä¸Šã€‚
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-01-01" }