course_name = "数字图像处理"
repo_type = "normal"
course_code = "AUTO3003"
description = ""

[[lecturers]]
name = "陈浩耀"

[[lecturers]]
name = "吴晓军"

  [[lecturers.reviews]]
  content = """全英文课件，由于内容多学时少所以讲得很快。考勤的方式是上课时让所有同学在一张纸上写名字，据我观察出勤率很低。
学习内容之间的耦合关系比较强，所以如果某一节没听，后面想跟上就很难了。但是不必担心，大家都一样跟不上。"""
  author = { name = "", link = "", date = "" }

[[textbooks]]
title = "数字图像处理（第四版）"
book_author = "[美] Rafael C. Gonzalez / [美] Richard E. Woods"
publisher = "电子工业出版社"
edition = "第四版"
type = "textbook"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "图像工程（第4版）上册"
book_author = "章毓晋"
publisher = "清华大学出版社"
edition = "第4版"
type = "reference"
author = { name = "", link = "", date = "" }

online_resources = []
course = []

[[exam]]
content = """考试为半开卷，允许携带计算器和一张 A4 纸小抄。
题型包括填空题、简答题。

考试会涉及需要理解、实操的知识，例如给出图像形态学操作后的结果，只凭小抄是解决不了的。

如果想考高分，除了~~要到~~准备一份高质量的小抄，建议至少理解作业里的题是怎么做的。"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2025-01-01" }

[[lab]]
content = """**实验**均为实物实验，2024 年的实验内容可以参考 [MaxwellJay256/dip_ws_2024](https://github.com/MaxwellJay256/dip_ws_2024)。

现场验收，不需要写实验报告。

建议课前准备好代码，因为除非自己配置环境，实验必须在实验室提供的笔记本电脑上进行，至于电脑上有没有 VS Code、ChatGPT 等工具就不一定了。如果空着手来，就等着一行行在文本编辑器里写代码吧😈，包拖堂的。

**课程设计**则是利用实验室的移动机器人，实现基于视觉的导航任务，约等于前面实验的综合应用。

允许一人独立完成或者两人组队，分数上没有区别。

课设是结课后才开始的，由老师发布任务，指定实验室开放时间，最后在一两天内集中**考核**和**答辩**。

1. 考核由老师现场验收任务的完成情况。陈老师比吴老师严。
2. 答辩由助教负责，展示一下任务完成的思路，基本上不可能为难你。"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2025-01-01" }

[[advice]]
content = """数图整体不难，考试也不涉及复杂的计算，但课程的安排使得整个战线很长。
表面上看，授课只持续半个学期，但实际上期末考试结束了，课设还没开始，对于想要速通拿到学分的朋友会有点难受。

就知识本身而言，数字图像处理对于机器人竞赛的中的视觉部分等实际应用还是有一些帮助的，毕竟处理图像是理解图像的前提。"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2025-01-01" }

[[related_links]]
content = "MaxwellJay256/DDR4: https://github.com/MaxwellJay256/DDR4"

[[related_links]]
content = "longlin 的课设幻灯片: https://pre.longlin.tech/"

[[misc]]
topic = "作业"
content = "作业基本来自《数字图像处理》的课后题。原书中只有部分题目给出了参考答案。"
author = { name = "", link = "", date = "" }