course_name = "自然语言处理"
repo_type = "normal"
course_code = "COMP3021"

[[lecturers]]
name = "xrf"
  [[lecturers.reviews]]
  content = "NLP 经验非常丰富的教授，为人和蔼可亲，欢迎大家去他的实验室学习深造。"
  author = { name = "", link = "", date = "" }

[[exam]]
content = "以前都是英文题面英文作答，今年因为疫情线上上课最后改成中文题面中文作答。开卷，建议带完整 PPT。"
author = { name = "", link = "", date = "" }

[[exam]]
content = "2023年的考题基本上以概念题为主，有些能在PPT上找到答案，有些需要靠自己的理解，建议带上完整PPT。"
author = { name = "", link = "", date = "" }

[[lab]]
content = """
三人组队，打 BDCI 上的比赛。
需要 Python 基础和深度学习框架基础，助教会花两节课时间教大家。
"""
author = { name = "", link = "", date = "" }