course_name = "操作系统"
repo_type = "normal"
course_code = "COMP3001"

notices = """
两位授课老师风格迥异，但是并不影响考试的公平性——因为考试考得基本跟上课关系不太大。
"""

[[lecturers]]
name = "刘川意"
  [[lecturers.reviews]]
  content = """
  上课抽点回答问题。
  PPT 基本是《操作系统导论》的原版英文 PPT。
  助教非常负责。
  不一定课前发 PPT，基本随缘。
  """
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "夏文"
  [[lecturers.reviews]]
  content = "讲课很专业。中文 PPT，内容多，总的参考《CSAPP》。"
  author = { name = "", link = "", date = "" }

[[textbooks]]
title = "Operating Systems: Three Easy Pieces (操作系统导论)"
book_author = "Remzi H. Arpaci-Dusseau / Andrea C. Arpaci-Dusseau"
publisher = "Arpaci-Dusseau Books"
edition = ""
type = "textbook"

[[textbooks]]
title = "Computer Systems: A Programmer's Perspective (CSAPP)"
book_author = "Randal E. Bryant / David R. O'Hallaron"
publisher = "Pearson"
edition = "3rd Edition"
type = "reference"

[[textbooks]]
title = "王道考研系列：操作系统考研复习指导"
book_author = "王道论坛"
publisher = "电子工业出版社"
edition = ""
type = "reference"

[[exam]]
content = "可以参考《王道考研——操作系统》进行复习。"
author = { name = "", link = "", date = "" }

[[lab]]
content = """
实验大多基于 Linux，如果可能的话最好提前接触，学习一些简单的命令行操作与操作命令。
2018 级的前四个实验选用了基于 MIT6.828/6.S081（2019）课程的 XV6 作为实验平台，完成一些指定任务；最后一个实验需要设计一个文件系统。
操作系统的实验都比较困难，因而需要花费比较长的时间。好在 MIT 的系列实验都有“巨人的肩膀”相助（CSDN）；最后的系统设计，确实需要考验一些功夫，包括系统整体设计与函数封装、指针使用等问题，而且可能出现各种 BUG，需要花一些时间。
最后一节实验课会进行课堂检查，会要求现场改代码、解读代码等等，所以需要做好应对之策。
可以多问老师。助教可能派不上太大用处。
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """
操作系统确实是 CS 的一门很重要的课程，好好学习必不会吃亏！
课程可能会设置「附加题」，保证平时分 + 实验分拉满。请审慎选择！
"""
author = { name = "", link = "", date = "" }

[[misc]]
topic = "实验变化"
content = "每年的实验都不太一样。"
author = { name = "", link = "", date = "" }