course_name = "面向领域的计算机系统设计与开发实践"
repo_type = "normal"
course_code = "COMP2029"

notices = """
2018 级大三下、2019 级大四上开设 COMP2024B 软件设计与开发实践B Design and Practice of software (B)。
2020 级起改为大四上开设 COMP2029 面向领域的计算机系统设计与开发实践 Domain Oriented for System Design and Practice。
"""

[[course]]
content = """
课程以导师课题分组带领学生的形式授课，需要在选课环节先选导师，进行学生导师互选。
课程可以做毕设相关内容，毕设导师不在授课教师名单内也可以联系老师进行答辩验收结课。
"""
author = { name = "维护者", link = "", date = "" }