course_name = "机器学习"
repo_type = "normal"
course_code = "COMP3006"

[[lecturers]]
name = "丁宇新"
  [[lecturers.reviews]]
  content = """
  与计导是同一个老师。
  PPT 内容总体中规中矩，从书上摘下的内容。
  """
  author = { name = "", link = "", date = "" }

[[lab]]
content = """
会做一个kaggle上的TItanic乘客遇难情况预测，可以上*CSDN*寻求前人的帮助，给分与预测的准确率（在班上的排名）有关。
不卷的话，其实还是压力不大的。但是需要**使用Python**完成Project，建议提前学习。
"""
author = { name = "", link = "", date = "" }

[[exam]]
content = "18级因为疫情取消考试。但是据说17级有人被挂科了。"
author = { name = "", link = "", date = "" }