course_name = "计算机专业导论"
repo_type = "normal"
course_code = "COMP2001"

notices = """
曾经 COMP2001 计算机专业导论为考试课，2 学分。
24 级开设 CAEC 计算机与电子通信集群专业导论，25 级开设 COMP1013 计算机专业导论。
24 级和 25 级内容较 22 级以前均有大幅删减。
"""

[[lecturers]]
name = "刘洋"
  [[lecturers.reviews]]
  content = "上课风格活跃（奈何课程枯燥乏味）。"
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "丁宇新"
  [[lecturers.reviews]]
  content = """
  PPT 的话比较硬核，都是一些核心知识。书本知识排版很差，没有必要看书本。
  上课若能跟上老师节奏，不妨听课；但跟不上的话就没有必要了。课前发 PPT。
  """
  author = { name = "", link = "", date = "" }

[[online_resources]]
title = "中国大学MOOC 的哈工大计算机导论"
url = ""
description = "网课资源"
author = { name = "", link = "", date = "" }

[[exam]]
content = """
（注：以下为原来考试课时代的情况）
期末考试难度整体适中，打分较友好，最高分 93 左右，平均分 80 左右。挂科率大约在百分之一到百分之二。
考试主要考查各种知识的概念，主要是简答题，要记背的东西非常多！！
考试复习时，建议以背诵 PPT 为主，能背多少背多少，同时也可以将老师给的主观题答案背下来。
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """
（注：以下为原来考试课的情况）
作业一定要认真完成！！每个老师作业不一样，比如我们老师所有作业加起来共 100 道选择题，错一道题最终就扣一分，导致有同学作业分是 47 分（满分 100）!
"""
author = { name = "", link = "", date = "" }