course_name = "电路实验IA"
repo_type = "normal"
course_code = "EE1012A"

[[lecturers]]
name = "姜老师"
  [[lecturers.reviews]]
  content = """
  授课风格：幽默风趣，认真负责
  是否需要认真听讲做笔记：实验过程中的数据会记录，下课前需交给助教检查
  """
  author = { name = "", link = "", date = "2023-06-01" }

[[course]]
content = """
虽然该课属于考察课，且是实验课，但本课程所花费的时间会十分巨大。
实验本身很有趣，但填写实验报告是一项非常累人的事，所以在课程后期大家都倾向于借鉴他人写好的实验报告略做修改提交（指实验数据以外的部分）。
实验课结束后也会预留大量补做时间，所以应该不用担心挂科问题。
本课程在 MOOC 上也有教学视频，可以在课前预习观看，不过其中内容与实际教学存在出入。
"""
author = { name = "", link = "", date = "2023-06-01" }

[[advice]]
content = """
做实验前一定要先做好预习工作，例如：
- 提前将理论值计算出：在实验过程中即可发现测量错误以纠正
- 提前熟悉要使用的设备：如此在测量数据过程便能更加得心应手

提前向老师讨要 PPT 或许最节省时间，事实上做完实验并检查完数据后就可立即离开，不需要等下课（不过很多同学都是下课后还没完成，需要另找时间补做）。
"""
author = { name = "", link = "", date = "2023-06-01" }