course_name = "电路实验IB"
repo_type = "normal"
course_code = "EE1012B"

[[lecturers]]
name = "姜倩倩"
  [[lecturers.reviews]]
  content = "很好的老师，会尽力帮助大家做实验"
  author = { name = "", link = "", date = "" }

[[textbooks]]
title = "电路实验IB 实验指导书"
book_author = "赵飞 / 王丹丹"
publisher = ""
edition = ""
type = "textbook"

[[textbooks]]
title = "电路实验教程"
book_author = "王灿 / 吴屏"
publisher = "哈尔滨工业大学出版社"
edition = "2020.11（2023.1 重印）"
type = "textbook"

[[online_resources]]
title = "Longlin 的电路实验IB仓库"
url = "https://github.com/longlin10086/HITSZ-CircLab"
description = "个人整理好的电路实验IB 仓库以供参考"
author = { name = "Longlin li", link = "https://github.com/longlin10086", date = "2023-12-01" }

[[advice]]
content = """
同大物实验一样，大部分电路实验报告也是非常耗时的，只不过大物你可以通过选课避免掉一些难做的实验，而本实验不行。

本实验的难点主要有：**实验操作**、**计算与绘图** 两点。
1. 实验操作：本人实际体验下来，大部分仿真类实验都是比较好做的，只要照着指导书上的操作一步一步来即可。而实操的内容则往往存在很多同学当堂难以完成，需要另找时间课后补做。
2. 计算与绘图：本学期电路实验会充斥大量计算绘图，因此掌握一门绘图工具库是比较好的选择，这在之后的实验中也会经常使用到。
"""
author = { name = "Longlin li", link = "https://github.com/longlin10086", date = "2023-12-01" }

[[advice]]
content = """
尽管每学期的助教不一样，但总体来说助教检查会比老师更好说话。当实验报告某处出现错误时，老师往往会让你重做一遍，而助教则可能会告诉你正确结果范围，让你课后再修改。
"""
author = { name = "Longlin li", link = "https://github.com/longlin10086", date = "2023-12-01" }