course_name = "数字电子技术实验"
repo_type = "normal"
course_code = "EE1010"

# 全局注意事项/简介
description = """
本课程为考查课，无期末考试。
六次实验，每次实验是 4 学时，任务量比较大，建议提前预习。
"""

# 成绩评定
[[online_resources]]
title = "Verilog 教程 (菜鸟教程)"
url = "https://www.runoob.com/w3cnote/verilog-tutorial.html"
description = "推荐预习教程，软硬件结合实验必备。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[online_resources]]
title = "Easy 云课堂"
url = "https://www.easyketang.com/"
description = "实验报告提交与预习平台。电脑版建议使用网页端。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

# 核心课程评价区块
[[course]]
content = "授课教师：实验中心教师+（部分班级）理论课教师+二名本科生助教。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

# 实验相关评价/建议
[[lab]]
content = """
听课建议：先讲一小会儿原理和注意事项（需要听一下，因为有些器材的使用方法不那么直观）。然后就自己做实验，有问题可以问助教。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[lab]]
content = """
对于硬件实验（利用 74 系列中规模集成芯片完成的实验），主要考查的是细心程度。
1. 上课前就设计好电路，并仔细分析其正确性，边上课边搭建电路大概率不能按时完成。
2. 有同学接线时候贪快，总是接错线，到最后总要在密密麻麻的线里面找错误，这是非常费时费力的。与其犯了错误事后缝缝补补，不如一开始就耐住性子认真做好。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[lab]]
content = """
对于软硬件结合的实验（利用 Verilog 语言 + FPGA 实现逻辑电路），由于课上能学习 Verilog 的时间很少（基本都要用来完成任务），讲解的 Verilog 语法也很有限，大家在上数字电子技术实验有关 Verilog 的内容前，务必认真预习！
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

# 课程安排
[[schedule]]
content = "六次实验，每次实验是 4 学时，任务量比较大。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

# 相关链接
[[related_links]]
content = "https://github.com/MaxwellJay256/FPGALab_2024"

# 兜底板块：预习与提交说明
[[misc]]
topic = "预习与提交要求"
content = """
1. 实验报告在 Easy 云课堂（微信小程序或网页端网上提交），无需提交纸质版。
2. 关于预习题（2024 春更新）：上课前已经不需要打印纸质版预习题，但仍需在 Easy 云课堂上完成预习题后方可看到当次实验的具体内容（实验任务、指导书、教学视频等）。
3. 早期要求（仅供参考）：上课前需要完成预习题并打印出纸质版，当堂检查。
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "" }