course_name = "专业综合实践"
repo_type = "normal"
course_code = "EE304X"

notices = """
21 级以前，电气专业课程设计包括大三上开设 EE3006 技术基础课程设计，大三下开设 EE3009 专业课程设计，大四上开设 EE3008 专业创新设计。

22 级起，电气专业课程设计改为大三上开设 EE3041 专业综合实践I，大三下开设 EE3042 专业综合实践II。

其中，技术基础课程设计和专业综合实践I为设计示波器，专业课程设计和专业综合实践II为设计反激电源。
"""

[[lecturers]]
name = "王宏"
  [[lecturers.reviews]]
  content = """
  电气自己的整蛊大师（
  套件记得提醒他购买，报告给分较为随机。
  """
  author = { name = "", link = "", date = "" }