course_name = "电力系统分析"
repo_type = "normal"
course_code = "EE3015"

# 全局注意事项/简介
notices = """
这门课是由电气工程基础，电力系统稳态分析，电力系统暂态分析合并而来。

21 级之前，大三上必修《电力系统基础》（3 学分，授课 48 学时，考试），选择电力系统及其自动化模块作为主修的学生在大三下必修《电力系统分析》（3 学分，授课 48 学时，考试）。
22 级之后，学生不再区分方向，两门课程合并为本门课程。
"""

# 成绩评定