course_name = "毛泽东思想和中国特色社会主义理论体系概论"
repo_type = "normal"
course_code = "GEIP1018"

notices = """
老师称 2024 年是 “课程改革的元年”，未来教学方案可能还会有调整。
2023 年版教材将习概的内容分离了出来，因此与 2021 年版内容区别较大。
"""

[[textbooks]]
title = "毛泽东思想和中国特色社会主义理论体系概论"
book_author = ""
publisher = "高等教育出版社"
edition = "2023 年版"
type = "textbook"

[[exam]]
content = "2024 年期末考试开始一校三区统一命题，闭卷考试。"
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2024-07-06" }

[[exam]]
content = "2025 年期末考试难度有所下降，题型略有变化。"
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-26" }

[[advice]]
content = """
本课程自 2019 年起变为考试课。
以前本课程考前会划重点，但在 2021 年春季，由于有同学举报，政治类课程开始都不划重点。
在参考本仓库时，请注意资料年份。一些较老且较小的资料出于保留课程历史沿袭的原因被放入了仓库之中。
"""
author = { name = "Origami404", link = "https://github.com/Origami404", date = "2025-01-01" }

[[advice]]
content = """
如果有串讲，相信串讲（然而 2023 年出现了反向串讲）。
如果没有串讲，尽早开始整理知识点，尽早开始记忆。
"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2024-07-06" }

[[advice]]
content = "2024 年的考试证明串讲有用但不完全有用，拓展并记忆串讲的内容只能考上 80~90，若对自己有更高的要求可以面向考研复习"
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-12" }

[[advice]]
content = "2025 年适逢教学评估，一校三区取消串讲环节。但所幸，最后考试内容大部分在考研复习资料范围内（只有两题多项选择题不在）。"
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-26" }