course_name = "矩阵分析"
repo_type = "normal"
course_code = "MATH4001"

[[lecturers]]
name = "牛牧青"
  [[lecturers.reviews]]
  content = """
  授课风格：讲解细致，富有耐心。ppt 列出要点，用详细的板书来讲解例题、补充注解，以及补充证明的细节。
  听课建议：认真听讲，拍板书，课后再整理。
  点名方式是提问。作业整个学期布置 10 道题。
  """
  author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-11-01" }

[[lecturers]]
name = "朱萍萍"
  [[lecturers.reviews]]
  content = "暂无具体评价。"
  author = { name = "维护者", link = "", date = "2025-11-01" }

[[lecturers]]
name = "樊一民"
  [[lecturers.reviews]]
  content = "暂无具体评价。"
  author = { name = "维护者", link = "", date = "2025-11-01" }

[[lecturers]]
name = "郭早阳"
  [[lecturers.reviews]]
  content = """
  2025 秋开始，不再教授此门课程。
  教学内容和上面三位老师有较大差别。
  """
  author = { name = "维护者", link = "", date = "2025-11-01" }

[[lecturers]]
name = "严质彬"
  [[lecturers.reviews]]
  content = "2024 秋开始，不再教授此门课程。"
  author = { name = "维护者", link = "", date = "2025-11-01" }

[[textbooks]]
title = "矩阵分析"
book_author = "史荣昌 / 魏丰"
publisher = ""
edition = "第 3 版"
type = "textbook"

[[online_resources]]
title = "严质彬老师《矩阵分析》授课视频"
url = ""
description = "视频教程"
author = { name = "维护者", link = "", date = "2025-11-01" }

[[course]]
content = """
主要内容：
- 线性空间和线性变换（线性空间的概念，基、坐标与维数，子空间，线性变换的概念及矩阵表示，等价与相似，特征值与特征向量）；
- $\\lambda$ 矩阵和 Smith标准型（$\\lambda$ 矩阵，单位模阵，Smith 标准型的概念与计算，不变因子、行列式因子、初等因子(组)，特征矩阵，特征矩阵相抵与矩阵相似，Jordan 分解定理）；
- 内积（内积与内积空间，Gram 矩阵及其性质，施密特正交化与 QR/UR 分解，酉矩阵与酉相似，正规矩阵与 Hermite 矩阵，奇异值分解）
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-11-01" }

[[exam]]
content = """
- 考试题型是：判断、填空、计算、证明。
- 每个老师是独立出题，所以一定不要走错考场。当然，2025 秋的教学内容都一样，所以这点要求关系就不大了。
- 考试**不允许携带计算器**。非常考验对初等行变换及行列式的计算能力。
"""
author = { name = "维护者", link = "", date = "2025-11-01" }

[[advice]]
content = """
矩阵分析的许多概念会在实际工程中被大量用到。课堂上的内容实际上非常有限，如有兴趣或需要的同学，可以进一步深化学习线性代数（参看 [控制理论中的代数基础](https://hoa.moe/docs/sophomore-spring/auto2006/)），或是有关数值计算/凸优化/最优控制等进阶应用型知识，感受矩阵分析的威力。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-11-01" }