course_name = "设计与制造 C"
repo_type = "normal"
course_code = "MECH3041"

[[lecturers]]
name = "吴洋"
  [[lecturers.reviews]]
  content = "授课风格：有考勤。"
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "胡泓"

[[lecturers]]
name = "王焦乐"

[[exam]]
content = """
考试不会考到特别冗长繁琐的公式，更多的是设计准则类。主要还是背一些重要、好记的公式。

这门课知识点很多，但课程大纲的「了解」/「掌握」不能用来判断考试重点/范围。比如**齿轮传动的设计准则**，大纲写了解，但连续两年都考了简答。
"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01-01" }

[[advice]]
content = "这门课没有小作业，复习难度颇大，建议参照往年题、多看 PPT 例题。"
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2026-01-01" }