course_name = "面向领域的计算机系统设计与开发实践"
repo_type = "normal"
course_code = "COMP2029"

# 核心课程评价区块
[[course]]
content = """
课程以导师课题分组带领学生的形式授课，需要在选课环节先选导师，进行学生导师互选。
课程可以做毕设相关内容，毕设导师不在授课教师名单内也可以联系老师进行答辩验收结课。
"""
author = { name = "维护者", link = "", date = "" }
