course_name = "电磁场"
repo_type = "normal"
course_code = "EE2003"

# 授课教师 (Lecturers)
[[lecturers]]
name = "张弦"

  [[lecturers.reviews]]
  content = """
  授课风格：活力满满，超级讲课人
              听课建议：在前期速度较慢的时候边做笔记时注意理解相关推导，后期速度起飞时课后及时整理上课内容。
  """
  author = { name = "", link = "", date = "" }

# 教材与参考书(不需要author)
[[textbooks]]
title = "工程电磁场导论"
book_author = "冯慈璋 / 马西奎"
publisher = "高等教育出版社"
edition = "第四版"
type = "textbook"

[[textbooks]]
title = "电动力学导论"
book_author = "David.J.Griffiths"
publisher = ""
edition = "第三版"
type = "reference"

[[exam]]
content = """考试题目大多出自PPT例题、作业题、MOOC测试题，有许多概念性辨析的题目，注意理解相关概念，平时熟练掌握的话并不难以完成。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-01" }

[[lab]]
content = """实验共两个，分别是使用MatLab进行DFM仿真和适用FEMM软件进行DEM仿真。这两种方法是电磁场数值分析的两种重要方法。初上手可能会被卡住，指导书看不懂时多像老师提问。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-01" }

[[advice]]
content = """
第零章是矢量分析，作为全书的数学基础。第一章由熟悉的静电场分析为全书打下分析方法基础，接着恒定电场、恒定磁场，再到时变电磁场和准静态电磁场，后续的分析思路都与第一章类似。

由于学时不够，因此第一章结束后速度会越来越快，注意各场之间的类比和区别对比，运用**类比**和**对比**的方法进行学习。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-01" }

[[advice]]
content = """
老师讲的很好，备考时主要复习PPT，作业题目和MOOC题目。

MOOC尽量少丢分，不划算。
"""
author = { name = "SSC", link = "https://github.com/SSC202", date = "2024-12-01" }
