course_name = "大学英语"
repo_type = "normal"
course_code = "LANG100X"

# 授课教师 (Lecturers)
[[lecturers]]
name = "景怡"

  [[lecturers.reviews]]
  content = """
  上课会分享自己的留学与学术经历，如果认真听，可以学到不少干货。
              有签到，均在雨课堂进行；有签到二维码、课上小测两种形式。
              上课按照座位表坐，老师也会随机点人回答问题。
              ~~漂亮~~
  """
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-01-01" }
[[lecturers]]
name = "韩烨"

  [[lecturers.reviews]]
  content = """
  上课按座位表坐，且有较多互动。
              课后作业很多，每周完成口语 + 听力 + 阅读 + 可能的写作，需要花费不少时间，而且平时分中的作业部分严格按平台成绩打分。
              但是老师的英语水平确实很高，和她交流能学到一些英语知识。
  """
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "毕鑫(Lotus)"

  [[lecturers.reviews]]
  content = """
  上课座位任意，不点名，回答问题一般以传话筒形式，即使点名点到没来的也不会扣分。
              有一次 pre（大一下），分享你们组感兴趣的一篇学术文章。
              老师上课节奏很慢，而且~~口音好听~~。
  """
  author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01-01" }
[[lecturers]]
name = "毛成婷"

  [[lecturers.reviews]]
  content = """
  上课按座位表坐，需要用雨课堂二维码进行签到，一般按座位顺序以传话筒方式回答问题，也有随机抽人但次数比较少，题目不会也没关系，会跳到下一个人，每人一节课只需要回答一个问题。
              课后作业还好，每周完成口语或听力或阅读或可能的写作四种任务中的一个，不刷分的话半小时左右就可以完成，平时分中的作业部分严格按平台成绩打分。
              不强制要求买书，课堂提供的课件足以进行学习，但要求自带纸质本子用来完成听力任务。
              有小组作业，内容为自选方向进行一次英语演讲，要求四人一小组制作 ppt，并轮流或指派人进行课堂演讲，有两节课进行专门评分。
  """
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "肖雯琪"

  [[lecturers.reviews]]
  content = """
  上课随便坐，有点名但是内容都较为简单，签到次数非常少，没来不扣分但是来了会有额外加分（不少）。
              课后作业非常少，且会开通补交通道。
              老师人非常好，会带着大家织香囊~~端午节特色~~。
  """
  author = { name = "Cecilia", link = "https://github.com/mircecilia", date = "2025-06-01" }

# 网络资源（电子书、网课等）
[[online_resources]]
title = "《四、六级备考指北》"
url = "https://hoa.moe/blog/cet-intro/"
description = "如果你想了解四、六级考试，可以查看我们的博客"

# 核心课程评价区块
[[course]]
content = """
自 23 级起，大学英语改为三学期：
- 大一秋季学期的大学英语 A（LANG1006）为听说课，教材是视听说教材，训练英语听说能力
- 大一春季学期的大学英语 B（LANG1007）为论文教学课，教材是《学术英语（理工）》，训练英文论文阅读能力
  - 大学英语 A 和大学英语 B 的 A/B/C 班并无太大差别，老师亦是轮换教学
  - 作业量与分级无关，而是取决于老师
- 大二秋季学期的大学英语 C（LANG1008）为英语提高训练，涉及听说读写四个方面内容。
  - 大学英语 C 的 A 班不需要上课，但 23 级的 A 班需要完成**大量**作业
  - B 班需要完成 MOOC 课程
  - C 班需要参与线下课
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-02-01" }

[[exam]]
content = """
自 23 级起，每学期的期末考试与大一秋季学期英语分班考试结构一致，试卷结构为：
25 题四级听力 + 10 题雅思听力（1 篇文章）+ 2 篇四级阅读 + 1 篇雅思阅读 + 1 篇短文填词 + 1 篇雅思大作文（议论文）。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2024-12-01" }

# 兜底板块
[[misc]]
topic = "分班与免听"
content = """
- 大学英语 A 的分班由开学考试成绩决定，大学英语 B 的分班由大学英语 A 的期末考试成绩决定，大学英语 C 的分班由大学英语 B 的期末考试成绩决定。
- 每学期分班后卷面成绩位于前 20% 左右的学生可以申请免听之后所有学期的英语。
- 免听的学生的课程成绩完全由期末考试卷面成绩决定，即期末考试占比 100%，无平时成绩，无需参与平时课堂和完成平时作业。
- 在免听学期的期末考试成绩跌出免听线则失去之后学期的免听资格。

细则还可参考文件 `深圳校区2023级本科生大学英语课程免修免听方案.docx`
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-02-01" }
