course_name = "设计与制造 A"
repo_type = "normal"
course_code = "MECH2019"

# 授课教师 (Lecturers)
[[lecturers]]
name = "金晶"
[[lecturers]]
name = "孙士龙"
[[lecturers]]
name = "王悦昶"
[[lecturers]]
name = "潘尔振"
[[lecturers]]
name = "黄海林"
[[lecturers]]
name = "冯宇"

[[advice]]
content = """
2024 秋作业评分是规格严格的扣分制，即每次作业满分 10 分，每个错误之处都会 -1 / -0.5，一直扣到 0 分为止。

这门课是将三维的物体用二维图像表示出来，听起来就是一个抽象的过程；所以平常可以多去工图教室观察实物。
"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-09-01" }
