course_code = "EE30XX"
repo_type = "multi-project"
course_name = "电气专业选修课"

description = """
【考查课】

电气专业的选修课开设于第三学年春季学期和第四学年秋季学期。

自 22 级起，电气专业的选修课不再区分电力系统及其自动化和电力电子与电机驱动两个方向，而是从全部课程中选择任意门修读满足学分要求即可。22 级要求 9 学分，23 级要求 8 学分，24 级要求 10 学分。
"""

[[courses]]
name = "电气传动自动控制系统"
code = "EE3004"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
      【成绩构成】: 课程报告 70% | 实验 30%
      【学时】: 总学时 32 | 理论 22 | 实验 10
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "詹瀚林"

    [[courses.teachers.reviews]]
    content = """
    讲电机控制相关的东西，FOC，SVPWM 等，然后还涉及很多很多自控方面的东西，难度在选修课程上也是挺难的了。电机控制方向的选修课，比较硬核或者是非常硬核。
        
            课程实验类似电机学的实验，照着指导书做就好了。
        
            课程报告老师是说自由发挥的，我做的是 FOC 的控制，还加了无感控制的一些东西，反正就是搭仿真写篇课程报告，其实还挺麻烦的。
    """
    author = { name = "ZSA", link = "", date = "2025-11-01" }

[[courses]]
name = "开关电源原理与设计"
code = "EE3011"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
      【成绩构成】: 课堂表现 50% | 课程报告 50%
      【学时】: 总学时 32 | 理论 22 | 实验 10
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "朱荣伍"

    [[courses.teachers.reviews]]
    content = """
    上课我听不懂在讲什么东西，相当于是电力电子技术这门课的延拓，会讲一些电力电子书里面王明彦老师没划重点的东西，想保研浙大电力电子的同学这门课建议选一下，然后认真搞懂里面的知识点，据说面试时会问到，而且问的比较细。
        
            实验难度较大，每年实验内容会有变化，借鉴不了往届学长学姐的，只能自己做，而且实验老师是王丹丹老师，规格严格。
    """
    author = { name = "LJH", link = "", date = "2025-11-01" }

    [[courses.teachers.reviews]]
    content = """
    主要讲开关电源定义、原理、设计等内容，是电力电子技术的拓展，会详细讲 Buck 电路、正激电路、反激电路这类电路，开关管的控涉及比较多自动控制原理的内容。实际要学的话还是比较难的课，而且在选修的课程中选难度顶尖的，但是如果是要走电力电子方向还是可以好好学一下的。
        
            课程报告直接将我们实验报告写成课程报告的形式，做的是 Buck 电路的仿真，网上可以搜到参考的资料，认真做还是做的出来的。
    """
    author = { name = "ZSA", link = "", date = "2025-11-01" }

[[courses]]
name = "分布式电源与新能源发电"
code = "EE3012"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
      【成绩构成】: 平时及实验 50% | 课程报告 50%
      【学时】: 总学时 32 | 理论 16 | 实验 16
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "潘学伟"

    [[courses.teachers.reviews]]
    content = """
    课程难度适中，学的东西是电力电子化的电力系统，主要是学新能源并网技术，和电力电子方向靠的也挺近。
        
            实验难度适中，正常不用拖堂做，有硬件实验和 PSIM 仿真软件实验。
    """
    author = { name = "LJH", link = "", date = "2025-11-01" }

[[courses]]
name = "智能电网"
code = "EE3016"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
      【成绩构成】: 平时 30% | 小组汇报 30% | 实验 40%
      【学时】: 总学时 32 | 理论 16 | 实验 12+4
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "吴婷"

    [[courses.teachers.reviews]]
    content = """
    平时分包括考勤、课上小测以及课后作业。课程难度适中，学的东西是电力系统规划/电力市场，主要就是运筹学和写代码。
        
            实验很简单，一堂课做两三个实验，不会写的直接问gpt就行，实验可以五分钟速通。
    """
    author = { name = "LJH", link = "", date = "2025-11-01" }

[[courses]]
name = "电力系统继电保护"
code = "EE3017"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
      【成绩构成】: 实验 60% | 课程论文 40%
      【学时】: 总学时 32 | 理论 20 | 实验 12
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "黄祈生"

    [[courses.teachers.reviews]]
    content = """
    课程难度较大，而且课时被压缩了有点难听懂，继电保护在别的电气强校（如西交）是电力系统方向的一门核心专业课，但由于哈深没有继保方向的老师，所以就随便上上得了。但是建议想保研外校（清浙交）电力系统和高压方向的同学最好不要选修这门课以及发电厂电力系统，因为面试时会问得很细，你答不上印象分会很差。
        
            实验有一定难度，完全不听课做实验会有点难度，建议还是去听一下课再做实验，实验老师是李文立老师，老师人很好，不会为难人。
    """
    author = { name = "LJH", link = "", date = "2025-11-01" }

    [[courses.teachers.reviews]]
    content = """
    主要讲电力系统中继电保护的内容，主要内容是三段式保护，课程实际上还是比较难的，但是考核比较简单。电力系统方向的选修课，如果作为考试课的话还算比较难的东西，但是如果是选修课那一堆公式不用记住的话还算可以接受。
        
            实验就是接线实验，有一个仿真实验会稍微难一点，但其实实际上有好好学的话是可以做出来的，做不出来可以相互帮助一下。
        
            课程报告是多个主题选择，可以做三段式阻抗保护（实验是三段式电流保护，可以参考实验和网上的教学来搭仿真），可以做看论文写文献综述那种形式。
    """
    author = { name = "ZSA", link = "", date = "2025-11-01" }

[[courses]]
name = "电力系统综合实验"
code = "EE3018"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
      【类型】: 实验
      【成绩构成】: 实验 100%
      【学时】: 总学时 24 | 实验 24
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "李文立"

    [[courses.teachers.reviews]]
    content = """
    （本研上为张弦老师，但是实际上是李文立老师在带）
            原来电力系统及其自动化方向的模块实验。
    """
    author = { name = "匿名", link = "", date = "" }

[[courses]]
name = "现代电机设计与CAD"
code = "EE3027"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1.5
      【学时】: 总学时 24 | 理论 16 | 上机 8
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "赵飞"

[[courses]]
name = "发电厂电气系统"
code = "EE3038"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1.5
      【学时】: 总学时 24 | 理论 24
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "梁亮"

[[courses]]
name = "电气前沿技术专题"
code = "EE4001"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
      【成绩构成】: 课程论文 100%
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "多个老师"

    [[courses.teachers.reviews]]
    content = """    多个老师一起上课，很轻松，一节课不去都没事，但我建议还是去听一下，老师有时会夹带一些“私货”，对开拓眼界还是很有帮助的。而且对保研人来说也能了解到每个老师的研究方向，可以基于此确定未来想做的方向和想跟的老师。除了朱院长上的那节课要考勤，其他老师基本不考勤。
    """
    author = { name = "LJH", link = "", date = "2025-11-01" }

[[courses]]
name = "智能控制基础"
code = "EE3021"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
      【成绩构成】: 平时 40% | 课程报告 60%
      【学时】: 总学时 16 | 理论 16
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "张东来"

    [[courses.teachers.reviews]]
    content = """    以小测形式考勤，上课的内容主要围绕模糊控制来讲，很轻松，想选张东来老师作为研究生导师的同学建议选这门课。
    """
    author = { name = "LJH", link = "", date = "2025-11-01" }

[[courses]]
name = "电力电子系统建模与仿真"
code = "EE3022"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1.5
      【学时】: 总学时 24 | 理论 8 | 实验 16
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "王灿"

[[courses]]
name = "电磁兼容基础"
code = "EE3023"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
      【学时】: 总学时 16 | 理论 16
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "和军平"

[[courses]]
name = "电机驱动控制系统设计"
code = "EE3024"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 2
      【学时】: 总学时 32 | 理论 24 | 上机 8
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "王宏"

[[courses]]
name = "电气测量技术"
code = "EE3026"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1.5
      【学时】: 总学时 24 | 理论 20 | 实验 4
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "梁仲明"

[[courses]]
name = "电能质量分析"
code = "EE3028"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
      【学时】: 总学时 16 | 理论 12 | 实验 4
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "叶剑"

    [[courses.teachers.reviews]]
    content = """老师已离职，故 22 级未开课"""
    author = { name = "匿名", link = "", date = "" }

[[courses]]
name = "高电压技术"
code = "EE3029"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
      【成绩构成】: 课堂表现 50% | 课程报告 50%
      【学时】: 总学时 16 | 理论 12 | 实验 4
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "谷雨"

    [[courses.teachers.reviews]]
    content = """    以小测形式考勤。上课上的很好但是只有16个课时，研究生想选电力系统和高压方向的同学建议选这门课，本科和硕士毕业想去电网就业的同学也建议选。实验难度适中，正常不用拖堂做，实验老师是李文立老师，老师人很好。
    """
    author = { name = "LJH", link = "", date = "2025-11-01" }

[[courses]]
name = "电力系统调度自动化"
code = "EE3030"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
      【学时】: 总学时 16 | 理论 12 | 实验 4
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "朱荣伍"

[[courses]]
name = "电力市场概论"
code = "EE3040"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1.5
      【成绩构成】: 实验 40% | 课程报告 60%
      【学时】: 总学时 24 | 理论 12 | 实验 6+6
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "黄祁生"

    [[courses.teachers.reviews]]
    content = """    讲电力系统在调度过程中市场方面的博弈关系，类似于数学建模，涉及经济学，还挺有意思的。实验就是代码填空实验，照着做就好了。课程报告是看论文写文献综述。
    """
    author = { name = "ZSA", link = "", date = "2025-11-01" }

[[courses]]
name = "电学量的量子计量导论"
code = "EE3043"

  [[courses.reviews]]
  topic = "基本信息"
  content = """
  【学分】: 1
      【学时】: 总学时 16 | 理论 16
  """
  author = { name = "系统提取", link = "", date = "" }

  [[courses.teachers]]
  name = "张东来"
