course_name = "理论力学II"
repo_type = "normal"
course_code = "EMEC1002"

# 授课教师 (Lecturers)
[[lecturers]]
name = "梁旭东"

  [[lecturers.reviews]]
  content = """
  授课风格：PPT 和例题讲解。例题中有有往年的考试题。
              听课建议：讲解到位，值得一听。
  """
  author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "" }
[[lecturers]]
name = "潘泽华、牛牧青"

  [[lecturers.reviews]]
  content = """
  分别负责静力学&运动学（至速度瞬心法）/ 运动学剩余部分&动力学。
              授课风格：干货满满，思路清晰，很赞。
              听课建议：认真听讲。课上要跟上，课下动笔再算一遍。
              2025 秋，牛牧青老师将独立负责整门课程，而潘泽华老师将与凌超老师合作。
  """
  author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }
[[lecturers]]
name = "凡友华"

  [[lecturers.reviews]]
  content = """
  授课风格：PPT 和例题讲解，有板书。听起来很困。
              几乎每节课都考勤。考勤形式是，PPT 上给出题目，让大家自备纸张作答，下课时上交。但是 2024 秋并没有限制上交的时间为下课，也即允许补交。
  """
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "" }

# 网络资源（电子书、网课等）
[[online_resources]]
title = "理论力学（本部出品课程）"
url = "https://www.bilibili.com/video/BV1Gg41197GP"
description = "静力学部分讲的不错，但运动学和动力学的老师念 PPT，听着可能很难受。"

[[online_resources]]
title = "平面简单桁架中零力杆的判断"
url = "https://hoa.moe/blog/zero-force-poles"
description = "相关博客文章"

[[exam]]
content = """
2024 年开始，理论力学的教学与 HIT 本部同步，一方面加入了期中考试，另一方面期末考试题由本部出题。
2024 的第一次期中考试非常简单，满分一大堆。
然而本部的期末考试题和过去深圳校区的考试题相比难度较大。题型分布：
- 1 道简答 / 简单计算题（10 分）
- 5 道计算题（90 分）

针对本部的期末考试难度，可以参考 exams 文件夹下的「哈工大理论力学2009-2016期末试题」进行复习。
"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2024-07-12" }

[[exam]]
content = """
2024 年的期末考试和本部统考，体现出了惊人的计算量和思考量，由于每道题目的过程都非常长，因此复习时特别需要注意：
1. 完整做出一道题的能力：读题 + 分析出大致解题思路，思考自己这道题的每一个阶段需要求什么，已知什么；在做题过程中及时更新「解题思路」和「已知信息」，主动往题目的待求量靠拢。
2. 积累常用模型的常见结论，包括均质圆在水平面上只滚不滑的速度、加速度分布；不同情况下绳子绕动滑轮的速度、加速度分布（这两个都很重要！）
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-12" }

[[exam]]
content = """
2024 秋期中考试相比于 2024 春难度飙升：
- 题目增多，依次是 4 道小计算和 4 道大计算。
- 分数相对不高，没有满分。

某教学班期中成绩分布情况：

| 60以下| 60~69  | 70~79  |  80~89 |  90~100 | 平均分  |
|---|---|---|---|---|---|
| 7  | 13  | 14  | 15  |  6 |  74 |

但期末考试出奇地简单，某教学班卷面中位数有 89 之高。
"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-02-01" }

[[advice]]
content = """不仅要看懂理论，更要动笔实战。不要只看答案，这样容易高估自己的水平。"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[advice]]
content = """习题指导上有部分答案错误，遇到时请大胆怀疑，积极讨论。"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-12" }

[[advice]]
content = """如果课后题有不懂之处，可以在B站搜索`理论力学哈工大第九版第x章课后题`，有不少讲题视频，质量还可以。"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2024-12-02" }
