course_name = "电力电子技术"
repo_type = "normal"
course_code = "EE3002"

# 授课教师 (Lecturers)
[[lecturers]]
name = "王明彦"

  [[lecturers.reviews]]
  content = """讲课一般，经常讲一大堆别的东西之后再开始上课。"""
  author = { name = "", link = "", date = "" }

  [[lecturers.reviews]]
  content = """22 级十分注重考勤，但是没有平时分。23 级不太考勤，整学期只点过三次名，且后两次主要点第一次点到没来的同学。"""
  author = { name = "", link = "", date = "" }

  [[lecturers.reviews]]
  content = """老师比较注重各知识点的理解贯通，因此四大拓扑的第一节课都讲的比较慢，而后面原理类似的会讲的比较快。"""
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "王丹丹"

  [[lecturers.reviews]]
  content = """
  22 级：实验报告要求十分高（毕设级别要求），很难拿分，建议十分认真的写。
              23 级：实验整体给分较高。
  """
  author = { name = "", link = "", date = "" }

# 教材与参考书(不需要author)
[[textbooks]]
title = "电力电子技术"
book_author = "王兆安 / 刘进军"
publisher = "机械工业出版社"
edition = "第 6 版"
type = "textbook"

[[exam]]
content = """
本门课有期中考试，2023 级改为阶段测验，老师留了一节课来完成。
由于有两个教学班，且为了防止邻桌抄袭，老师出了四份卷子，四份卷子考察的内容基本一致，在一些题目的细节上有所不同，具体见资料下载的试卷部分。
"""
author = { name = "", link = "", date = "" }

[[exam]]
content = """考试基本是大背诵的概念题，但是需要注意细节，PPT 建议反复看。"""
author = { name = "SSC", link = "https://github.com/SSC202", date = "2024-11-01" }

[[exam]]
content = """
考试与老师上课讲的内容强相关，考试的重点在平时上课中会提到。主要考察基本概念的理解，波形图绘制一般是考相对比较容易的（比如三相不会考全桥波形只会考半桥波形）。

阶段测验考过的内容期末不再考察，复习时注意不要多复习了。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2026-01-01" }

[[lab]]
content = """
实验内容：
- 22 级为三相全桥整流电路（实物）、降压斩波电路（仿真+实物）、反激电路（仿真）
- 23 级为三相全桥整流电路（实物）、变压器漏感影响（实物+仿真）、降压斩波电路（实物）、反激电路（仿真）

每届实验内容会有所改变，但主要内容不变，实验设备与电机学所用设备一致，注意接线正确，数据记录全面即可。实验报告的波形图需要额外处理，老师不允许交原始截图。
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """
本门课程是模电的功率部分的后续课程，主要包括：电力电子器件、电力电子拓扑和电力电子控制三部分。其中
- 电力电子器件仅需要了解外特性即可，不需要像模电一样了解管子内部原理。本门课程主要使用晶闸管和绝缘栅双极晶体管两类管子。
- 电力电子拓扑包括：整流电路（AC-DC）、逆变电路（DC-AC）、直流变流电路（DC-DC）、交流变流电路（AC-AC）四类电路拓扑，重点掌握各种电路的电路结构、变流原理以及输入输出波形。对于上课重点强调的部分还需掌握计算。
- 电力电子控制学时所限仅讲授一部分PWM控制技术，这部分知识点较多，且由于学时问题上课较快，课后要花时间记忆理解相关概念，以及典型PWM控制的输入输出波形。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2026-01-01" }

# 课程安排
[[schedule]]
content = """总学时 48，授课 40 学时，实验 8 学时。"""
