course_name = "中国近现代史纲要"
repo_type = "normal"
course_code = "GEIP1016"

[[exam]]
content = """
考试题型：选择题、简答题、材料题、论述题。

期末前老师会组织串讲。2023 年很多同学认为串讲内容没有重点所以不认真听。然而考试后把题与串讲内容比较，我发现串讲中的详略和考试涉及的知识是几乎一致的。

因此，如果有串讲，建议同学们认真听完，做好录制，复习的时候把讲到的内容听写一遍（如写成 word 或 markdown），整理出自己的一份“中国近现代史纲要”，然后按照它来背书，串讲没提到的少关注，考试时你就能体会到什么是大 win 特 win 了。

2024 年的近现代史串讲中，有非常多并未考察的知识点，而且在考前三天才组织，与 2023 年有一周相比，背诵难度属实增大不少——好在，串讲覆盖了所有的考试知识点。
"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2023-07-01" }

[[exam]]
content = """
2019 级近代史（考查课）是在疫情期间授课，因此考试改为线上开卷考，可以上网查资料，每道题有字数限制，复制粘贴满即可。

但 2020 级开始变为考试课，因此或许会变得更有趣。考试前有划重点，并且有好心同学整理了详细的答案。
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """
### 背诵方法论
这里我想介绍一种个人认为比较实用的，用于背诵*大段意义类文字*的方法。它并不能帮你减小背诵量，但是，如果你按这个思路背诵，就可能在考试中头脑糨糊时，尽快找到思路、唤醒记忆。

首先将意义分点（一般课本/串讲已经帮你分好）。
然后概括每个点的主题；一般来说，意义的主题分为**三个「普适类」和一个「特殊类」**。
「普适类」主题不外乎几种：
- 国家
- 社会
- 未来/发展
- 世界

特殊类则需要额外记忆，比如说抗日战争的胜利有「精神」，中国革命的胜利有「理论」等。
**首先背这个意义的主题**，然后再背诵具体的内容；在考试中突然忘记时，只需要遍历这个「意义表」以唤醒沉睡的记忆。

当然，再重复一次，你仍然需要完完整整地全文背诵，但如果采用这种方法，可以在思路断掉时尽快回忆起来。
"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2024-07-01" }
