course_name = "数据库系统"
repo_type = "normal"
course_code = "COMP3010"

# 授课教师 (Lecturers)
[[lecturers]]
name = "张晓峰"

  [[lecturers.reviews]]
  content = """  经验老到，对数据库这门课有自己的理解。从 18 级开始由 zxf 老师主管出考试题，由于老师有工业界背景，出的题常常让学生们摸不着头脑。具体可参加 `exam` 目录下的回忆。
  """
  author = { name = "", link = "", date = "" }

[[exam]]
content = """
> 太哈人了。

考试开放性题很多，需要对概念有极清晰的理解，但是题目很怪，完全不知道答的对不对。我认为可以说是所有科目中近乎最难解答的试卷。

具体可以参考 `exam` 目录。
"""
author = { name = "", link = "", date = "" }

[[lab]]
content = """
前几次实验还好，重头戏是后两次。

倒数第二次需要实现一个小型数据库系统，要有前后端，能在本地访问。对于没有开发经验的同学来说可能是速成前端了。正常耗时一周到两周（做得好看与否）。

最后一次实验需要实现五个查询处理算法（C 语言），代码封装得好可能需要 1k+ 行，封装得不好可能 3k+。正常耗时一周。
"""
author = { name = "", link = "", date = "" }

# 兜底板块
[[misc]]
topic = "助教"
content = """理论课助教应该只负责改作业。"""
author = { name = "", link = "", date = "" }

[[misc]]
topic = "作业"
content = """
两次作业，只覆盖了前几章的内容。
考试前会发布作业题的答案供复习。
"""
author = { name = "", link = "", date = "" }
