course_name = "机器学习概论"
repo_type = "normal"
course_code = "AUTO3019"

# 授课教师 (Lecturers)
[[lecturers]]
name = "熊昊"

  [[lecturers.reviews]]
  content = """
  有时考勤，发一张表格让大家写名字。
              讲解不算清晰。
  """
  author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-01-01" }

# 网络资源（电子书、网课等）
[[online_resources]]
title = "Machine Learning (2021 Spring)"
url = "https://speech.ee.ntu.edu.tw/~hylee/ml/2021-spring.php"
description = "国立台湾大学李宏毅教授课程（本课程完全照搬此内容）。"

[[online_resources]]
title = "Introduction to Generative AI (2024 Spring)"
url = "https://speech.ee.ntu.edu.tw/~hylee/genai/2024-spring.php"
description = "李宏毅教授 2024 年春季开设的生成式人工智能导论。"

# 兜底板块
[[misc]]
topic = "作业与考核详情"
content = """
作业、期末报告、大作业都是三人一组。
期末报告内容是：从一系列主题（见 assignments/2024 文件夹下的 Presentation.pptx）选取一个，做 ppt 并演讲。
平时作业有三个（每个 10 分），具体内容见 assignments/2024 文件夹（作业 2 文件量比较大，所以放在校内网盘里面了）。大作业同样见文件夹。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2025-01-01" }
