course_name = "自动化认知与实践"
repo_type = "normal"
course_code = "AUTO1001"

# 全局注意事项/简介 (多行文本)
description = """本课程开设自 2022 年，合并了过去工程制图基础、自动化专业导论、机器人设计与实践、机械设计基础 4 门课程。
"""

# 授课教师 (Lecturers)
[[lecturers]]
name = "楼云江"
[[lecturers]]
name = "袁晗"
[[lecturers]]
name = "杨月"
[[lecturers]]
name = "黄瑞宁"
[[lecturers]]
name = "陈浩耀"
[[lecturers]]
name = "熊昊"
[[lecturers]]
name = "熊小刚"
[[lecturers]]
name = "葛亚明"

# 核心课程评价区块
[[course]]
content = """
此为 2021 级内容。新的导论部分对原来内容有了较大程度的裁剪，但是仍然建议有兴趣的同学仔细阅读有关“自动化基本原理”的内容，对自动控制系统的思想、构成、实现方式有个初步认识。
课件放在校内网盘。

主要内容：

- 自动化的概念与发展简史
- 自动化基本原理（这部分原来由吴爱国教授负责讲授），包括：
  - 两类自动控制：开环与闭环
  - 自动控制的定性描述（方框图等）与定量描述（数学模型，如传递函数）
    - 建立控制对象的数学模型是自动化专业的核心知识
  - 自动控制系统的基本要求——稳、快、准，及描述方式
  - 自动控制系统的控制方式（前馈、反馈、串级、多回路……）
  - PID 控制律，PID 各环节的作用
  - 反馈的重要性，关注**不确定性**等概念，自动化与控制的关系
- 现代自动化初览（科普）
- 自动化专业培养目标、课程体系、学术体系、发展前景
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[course]]
content = """
删减后的导论部分授课内容如下。23 级由于和《系统与控制》同时授课，因此 Oliver Wu 所说的对自动控制系统的思想、构成、实现方式的认识可以交给专业课完成。

- 自动化的概念和发展简史（3 学时）
- 自动化基本原理（4 学时）
  - 开环和闭环控制
  - 自动控制系统的基本要求（快准稳）
  - 自动控制系统的控制方式（前馈、反馈、串级、多回路）
- 自动化专业的培养目标、课程体系、学术体系、发展前景（1 学时）
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-01" }

[[course]]
content = """
工程制图（共 16 学时）主要内容：

- 制图的基本知识（2 学时）
- 点线面体的投影（4 学时）
- 组合体（3 学时）
- 机件的表达（1 学时）
- Solidworks 的使用（6 学时）

机械设计原理（共 2 学时）主要内容：

- 机构的组成，机构自由度计算（重点）
- 平面连杆结构，有曲柄条件，压力角，死点位置
- 齿轮机构及渐开线齿轮相关计算
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-01" }

[[course]]
content = """
主要内容：

- 电学基本知识（电路基础）（2 学时）
- 直流电机驱动基本知识（重点关注 H 桥）（2 学时）
- 实验中会用到的各种模块（如超声波传感模块等）的用法（2 学时）
- Arduino 编程入门（4 学时）
  - 基本 I/O（Input 输入、Output 输出）、串口
  - 延时函数、中断（采集编码器信号等）
  - 其他外围设备编程
  - 参考网站：https://www.arduino.cc/reference/en/
- PID 控制律作用于实际系统，每个环节的作用（2 学时）
- 轮式机器人基本运动学（2 学时）
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[exam]]
content = """
2022 级自动化专业学生参与了这门课第一次考试，笔试内容主要来自课堂教学，例如电机驱动，电阻色环识别，Arduino 编程知识。
考试难度对于从未接触过机器人或单片机的同学来说并不是很友好，而且主要考的都是死记硬背的东西，因此在学生间的评价很差。
"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "" }

[[exam]]
content = """22 年，这门课的考试主要是大背诵，包括色环电阻识别（阻值和误差的填空）；手绘整个 H 桥电机驱动电路；机械设计部分没考；而工程制图部分由于课时被压缩，考试仅出了很简单的填空题以及画图题，无需掌握复杂的画图技巧。
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "" }

[[exam]]
content = """25 年，23 级的期末考试大背诵程度进一步加剧，全试卷只有一题计算自由度和计算沾边，剩下全是各种定义概念的大背诵，包括：工图某种视图的定义，机械原理中的定义，Arduino 编程，阿克曼驱动以及 H 桥驱动电路分析与设计，试卷部分考点很偏且答题量超大。试卷具体的大背诵内容参考仓库中的期末试卷回忆。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-01" }

[[lab]]
content = """
以下内容仅代表 2022 级的情况。2022 级的自动化认识与实践被安排在大一上学期，并且是考试课。

前期的实验课比较简单，是使用电子元件和 Arduino 开发板制作一些简单的项目，可以参考课件文件夹中的实验指导书提前了解。如果做这些项目时遇到了问题，建议在 [CSDN](https://www.csdn.net/) 和 [Arduino 官网](https://www.arduino.cc/) 上查找有关资料。老师布置的项目，别人肯定也做过。

如果是用到 Arduino 的实验，建议在上课前提前准备好程序，现场敲代码会比较浪费时间。实验虽然会发实验代码，但不建议直接照抄，理解代码会对后期小车代码的编写调试大有裨益。

实验的打分由老师或者助教完成，就是看实际的运行效果，要求并不非常严格。完成实验课上的附加题可获得额外加分。
"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "" }

[[lab]]
content = """
23 级（2025 春）并无大改动，但是改为了考查课，实验具体内容已补充如下。

| 实验项目 | 分值说明 | 满分 |学时 |
| 实验 1：仪器设备使用 + 变压器整流电路 | 全波波形 2 分 | 2 | 2 |
| 实验 2：电机驱动电路：互补信号产生、MOSFET 驱动、H 桥电路 | 电机只能一个方向转 3 分/如果一直没调通，接线给 3 分/ 7406、7407 波形输出调对 1 分 | 6 | 4 |
| 实验 3：Arduino 基础实验：呼吸灯、舵机遥感控制、温湿度显示 | 每个实验 1 分 | 3 | 2 |
| 实验 4：Arduino 提高实验：电机正反转、编码器数据读取、超声波测距 | 每个实验 1 分 | 3 | 2 |
| 实验 5：电机调速 | 两个电机同步调速 6 分/单个电机调速 4 分 | 6 | 2 |
| 实验 6：机械臂抓取：使用三个舵机完成定点抓取 | 控制一个舵机 2 分（共三个舵机） | 6 | 2 |
| 实验 7：使用摄像头、红外传感器完成巡线测试 | 摄像头数据读取与处理 3 分，红外传感器数据读取 1 分 | 4 | 2 |
| 实验 8：装车、调车、考核 | 分值要求见后期部分，不计入实验的 30 分中 | | 8 |

2025 年春，实验部分基本参考指导书就可以顺利完成，如果遇到问题，课上老师不太会给解答，需要自己解决。给分较轻松，完成实验即可。

实验不太愉快的点在于实验要求往往滞后发布，甚至在实验后才说明实验报告要求，部分实验要求反复更改，导致同学们无法及时获得实验要求正确进行实验。

2025 年春，实验要求上交 4 个实验报告，分别是：

- 报告 1：电机驱动电路的调试
  - 要求手动画出电路接线原理图，给定两组不同的 PWM 的占空比，记录 74LS06 和 7407 的输出波形（可以粘贴图片）；测量 2104 的 HO 与 VS 之间的电压值，测量 LO 与 GND 之间的电压值，分析该电压值下 MOS 管的导通顺序和电机的转动方向；测量并记录 2104 的 HO、LO 引脚的波形（可以粘贴图片）。需要分析电路调试过程中遇到的问题和解决方法。
- 报告 2：Arduino 实验：舵机遥感控制、编码器数据读取、超声波测距
  - 通过监视窗自行记录数据并分析数据结果。
- 报告 3：电机调速
  - 记录双电机调速的波形，图像需要包括两个电机的调速波形和零值、设定值对应的直线共四条曲线。
- 报告 4：机器人小车巡线控制
  - 以设计流程框图的形式展现小车巡线设计思路，即如何寻找到跑道上的黑线；两个电机如何实现的同速控制；如何实现左、右转弯；调试中遇到的问题分析。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-01" }

[[lab]]
content = """
后期老师会把实验室开放给学生，自行使用已有的零件搭建一辆能够——

- 使用红外线传感器巡线
  - 做到执行、转弯、直角转弯、走圆弧线等，不能冲出赛道
- 使用使用机械臂抓放物体
  - 在起点抓起物体在终点平稳放下，中途不能掉落
- 使用超声波避障
  - 22 级的避障功能是单独考核，考核避障的时候可以烧避障专用代码，不需要跑完整个赛道，只需要展示避障功能
- （23 级会有更多内容，敬请期待……）

——的小车。小车会在期末进行考核，根据完成任务的情况打分。

关于这个部分，**每一届自动化的学生都有很多故事想说 😅**，但是就不在这里展开了。

不过我们搜集了一些 2022 级同学的代码仓库，里面不仅有实用的代码，还有同学们分享的学习经历、经验和教程！
"""
author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "" }

[[lab]]
content = """
虽然部分自动化的学生对实验部分怨声载道，但从无到有搭建出一个寻迹小车确实能很大程度地提高学生的动手能力，特别是对于高中没有什么动手实践机会的同学来说，一进入大学就有这么 **重 量 级** 的实验确实是积累实践经验、提升实践技能的机会（但 23 级把这门课放在了大二下学期，就不好说了）

与 Wu 说的不同的是，我们的寻迹小车使用的控制板是 Arduino Mega 2560，使用 Arduino IDE 编写代码，逻辑非常简单，只需要写一个初始化部分和一个循环部分的代码，感觉和 C 语言没有什么相关性，甚至比 Python 语法都要简单。若对嵌入式软件有浓厚的兴趣，可以进入战队学习 STM32 的使用，这个单片机更加灵活，内容也更加丰富
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "" }

[[lab]]
content = """
25 年春，在 22 级的基础上，同样使用的控制板是 Arduino Mega 2560，使用 Arduino IDE 编写代码，将电机驱动由 L298N 换成了顺学长设计的 DRV7801 双驱电路板，同时各模块接口也集成到了 Arduino 拓展板上，只需自行焊接插件元器件，硬件上的难度大为降低。同时整车的机械结构由亚克力板换成双层金属板，车身更为牢固。但是重新要求机械臂需要自己设计并打印，使用参考模型的需要扣分。

考核要求：50s 内完成机械臂抓取物品，沿赛道巡线一圈到终点并放下物体，满分 30 分。车体完整基本分 10 分，夹爪未设计扣 3 分。巡线任务共 20 分，只完成机械臂抓取 5 分，只完成巡线 10 分，每超时 3s 扣 1 分，每重试一次扣 1 分。

加分项目：单独完成避障考核 +5 分；巡线总用时在 30s 内 +5 分。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06-01" }

[[advice]]
content = """
希望同学们认真完成实验，体会由物理系统——数学模型——物理实现的路径（如，针对物理系统的特性，设计 PID 控制律，再结合传感器将物理信号转换成电信号，利用单片机实现数字式的增量式 PID 控制算法），巩固 C 语言编程的知识。

希望同学们在实验过程中养成良好的习惯，爱护实验器材，维护好实验室的环境。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

# 相关链接
[[related_links]]
content = "Maxwell Jay - mega_12800: https://github.com/MaxwellJay256/mega_12800"

[[related_links]]
content = "longlin li - HITSZ_lab_project: https://github.com/longlin10086/HITSZ_lab_project"

[[related_links]]
content = "Chenx Dust - AutoCar: https://github.com/chenxijun/AutoCar"

[[related_links]]
content = "psp_dada - AutoCar-AUTO1001: https://github.com/pspdada/AutoCar-AUTO1001"

[[related_links]]
content = "Gaster - Harmony: https://github.com/WDGaster703/Harmony"

# 兜底板块
[[misc]]
topic = "课程介绍"
content = """自动化专业导论、工程制图、机器人设计与实践部分分别由不同的老师先后负责讲授。"""
author = { name = "", link = "", date = "" }
