course_name = "模式识别"
repo_type = "normal"
course_code = "AUTO5024"

# 授课教师 (Lecturers)
[[lecturers]]
name = "胡靓"

# 教材与参考书(不需要author)
[[textbooks]]
title = "模式分类"
book_author = "Richard Duda 等"
publisher = "机械工业出版社"
edition = "第 2 版"
type = "textbook"

[[textbooks]]
title = "模式识别"
book_author = "张学工 / 汪小我"
publisher = "清华大学出版社"
edition = "第四版"
type = "textbook"

# 网络资源（电子书、网课等）
[[online_resources]]
title = "《神经网络与深度学习》书籍主页"
url = "https://nndl.github.io/"
description = "邱锡鹏 著，机械工业出版社，2019"

[[online_resources]]
title = "《动手学深度学习：Pytorch 版》书籍主页"
url = "https://zh.d2l.ai/"
description = "第二版"

[[online_resources]]
title = "CS231n: Deep Learning for Computer Vision"
url = "https://cs231n.stanford.edu/"
description = "非常经典的课程，讲解的内容更加深入、全面、容易理解。"

[[online_resources]]
title = "CS231n 学习笔记"
url = "https://github.com/pspdada/LLM-Learning-Notes"
description = "psp_dada 整理的学习笔记"

[[exam]]
content = """半开卷，可带一张 A4 纸，可参考 notes 文件夹下的笔记。考试可以携带计算器。"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """本课程重实践，要求同学们具备编程解决模式识别相关问题的能力。因此，本课程考试难度不高（此处有待往届学生补充真实体会），没有考勤（2023 年秋情况），但是实验一定要去（证明你确实掌握了）。
"""
author = { name = "Hye", link = "https://github.com/Co-ding-Man", date = "2024-07-01" }

[[advice]]
content = """
模式识别这门学科中，课程框架大致可以划分为两个主要模块。课程的前半段聚焦于传统模式识别算法以及数据降维技术，这些是构建机器学习和数据分析基础的重要组成部分。而后半段则深入探讨神经网络相关话题，这是一个在现代人工智能领域占据核心地位的主题。

对于前半部分，在实际应用中，直接使用这些经典算法的机会可能较少，因为很多场景下已经被更为先进的技术所取代。因此，我认为了解这部分内容的思想和逻辑即可。

后半部分的神经网络部分个人推荐学有余力的同学去学习 CS231n，这是一门非常经典的课程，讲解的内容更加深入、全面、容易理解。

实验部分建议大家认真完成，不仅是因为实验所占课程的分值比重高，更是因为**代码能力**是现代大学生必备的技能之一，而实验的内容：通过 pytorch 库搭建神经网络，也是一个很好的毫不过时的练习机会。
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-12-01" }
