course_name = "数据结构与算法"
repo_type = "normal"
course_code = "COMP2050"

# 授课教师 (Lecturers)
[[lecturers]]
name = "任卫红"

  [[lecturers.reviews]]
  content = """
  授课风格：年轻老师，态度较认真，会比较认真地回答同学的问题，对于课程定位非常清楚，知识讲解清晰。但是有时会出现表意不清的现象（这和知识本身比较抽象也有关系）。
              听课建议：建议上课听讲+课后整理。
  """
  author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2023-06-01" }

[[exam]]
content = """（21 级情况）难度一般。授课内容中比较困难的点，如 KMP、AOV 网等，都不考。但是最好了解一下。"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2023-06-01" }

[[advice]]
content = """
代码的实现细节（即语法）是次要的（不要因为经常在语法上犯错或者数组越界之类的问题而认为这门课“难”而心生逃避，这样会妨碍对知识本质的理解！！），重要的是对恰当地组织数据以及分治等算法思想的理解。考试也不需要写出具体的代码。
数据结构、算法的知识很丰富，本门课只是入门，如果日后用到有关知识，大家还需要进一步深入学习。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2023-06-01" }
