course_name = "计算机视觉"
repo_type = "normal"
course_code = "COMP3029"

# 授课教师 (Lecturers)
[[lecturers]]
name = "sjy"

  [[lecturers.reviews]]
  content = """  人很和蔼，会在群里和大家聊天，课讲得深入浅出，看得出对 DL、CV 有很深的理解。
  """
  author = { name = "", link = "", date = "" }

# 核心课程评价区块
[[course]]
content = """CS131 的部分作业，还有一些作业找不到出处。提交 ipynb。"""
author = { name = "", link = "", date = "" }
