course_name = "模式识别"
repo_type = "normal"
course_code = "COMP3007"

# 授课教师 (Lecturers)
[[lecturers]]
name = "徐勇"

  [[lecturers.reviews]]
  content = """
  非常认真有趣的一个老师，会尽量举生活中的例子来帮助理解原理，会发放精心准备的课程讲义。
              PPT逻辑性比较强。
              授课风格总体比较轻松，要点会提前告知。
  """
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "张治国"

  [[lecturers.reviews]]
  content = """  考勤方式很友好，使用雨课堂签到（作业批改完成后会在批改完成后的下节课把作业带到教室里让同学们领取，如果人没到那么会被老师发现，不过不清楚这会不会被记录到考勤记录里）
  """
  author = { name = "", link = "", date = "" }

# 核心课程评价区块
[[course]]
content = """课程内容还算是比较难，想学好需要下一些功夫。不过考试难度比较简单，基本上听了一点内容或者过一遍讲义就不用担心不及格。"""
author = { name = "老学长", link = "", date = "" }

[[course]]
content = """课程前半段难度不高，后面两三章比较难。"""
author = { name = "老学长", link = "", date = "" }

[[exam]]
content = """
想不挂科是不难的，不用担心挂科。考试范围和上课的范围相比要小很多（老师会给出考试范围），不要求记忆公式和算法流程（但还是考了贝叶斯公式，不过也只考了这一个），无计算，有一些**送分题**。
但是，**有的选项PPT中根本没有**。复习时建议参考“模式识别-2022级期末复习指南”，里面按知识点对2023秋的期末试题进行了整理。
"""
author = { name = "2021级学长", link = "", date = "" }

[[exam]]
content = """
本人模式识别课的老师是张治国，不清楚其他老师的 PPT中是否有这些选项。
如果其他老师的PPT中有这些选项的话，22级的学弟学妹们在复习时可以互换一下PPT，避免遗漏考点。
如果没有的话，那想要拿高分就不能只看PPT了。
"""
author = { name = "2021级学长", link = "", date = "" }

# 兜底板块
[[misc]]
topic = "关于作业"
content = """2021级共3次作业，可以参考书上的例题来完成。"""
author = { name = "", link = "", date = "" }
