course_name = "数字逻辑设计"
repo_type = "normal"
course_code = "COMP2051"

# 授课教师 (Lecturers)
[[lecturers]]
name = "高翠芸"

  [[lecturers.reviews]]
  content = """  一个非常负责的老师，上课条理清晰，面对疑问也会耐心解答，PPT做得简洁明了，每节课前会提前发到群里，偶尔抽查点到，但是认真听课会对学习这门课程有很大帮助，建议按时上课。
  """
  author = { name = "criwits", link = "https://github.com/criwits", date = "2022-06-01" }
[[lecturers]]
name = "张春慨"
[[lecturers]]
name = "崔爱娇"

  [[lecturers.reviews]]
  content = """  崔老师非常认真负责，会尽量去认识班上的每位同学，因此前期点名较多。老师课上讲授细致，经常让同学回答问题，课下也会把PPT发到群里供大家复习。如果课上能跟着老师的节奏一起走，是非常有利于深化对所学知识的理解的。
  """
  author = { name = "PVZ&X", link = "https://github.com/wpj9362", date = "2026-01-01" }

# 教材与参考书(不需要author)
[[textbooks]]
title = "逻辑设计基础"
book_author = "Charles H. Roth,Jr / Larry L. Kinney"
publisher = "清华大学出版社"
edition = "7版"
type = "textbook"

# 网络资源（电子书、网课等）
[[online_resources]]
title = "潜伏的数逻实验仓库"
url = "https://github.com/capoo-fan/class-experiment/tree/main/%E6%95%B0%E5%AD%97%E9%80%BB%E8%BE%91%E7%94%B5%E8%B7%AF"
description = "相关实验仓库"

[[exam]]
content = """
考试难度中等，高分主要集中在 96，97 分段，较为友好，建议认真写作业，复习重点可以放在PPT上，尤其是各种模型的理解分析，掌握做题方法就可以。

考试成绩出的很慢，需要大海捞人，一个多月才出。
"""
author = { name = "criwits", link = "https://github.com/criwits", date = "2022-06-01" }

[[exam]]
content = """
考试题型：24秋和25秋的题型相似，有简答题、分析题、综合设计题（具体参考往年题）。试卷的考点主要集中在老师平时发的PPT上，老师也会把考试范围发给大家供参考，因此需要认真复习PPT的知识点和例题。
2025秋的数字逻辑设计考试，可能是由于变成考试课或者教学评估，难度有所提升，主要体现在试卷题量大，容易写不完。
"""
author = { name = "PVZ&X", link = "https://github.com/wpj9362", date = "2026-01-01" }

[[exam]]
content = """25 秋考试难度大幅度提高，且作业是根据正确率扣分的，大家记得认真做作业。"""
author = { name = "Cecilia", link = "https://github.com/mircecilia", date = "2026-01-01" }

[[lab]]
content = """
实验很难（难度因人而异，不过没人觉得简单），因为其对于逻辑和细节要求都很高，耗时普遍较长。分为课上与课下两部分，课上部分尽量按时完成，遇到困难一定要及时请教老师与助教，提高解决问题的效率，老师会把课上部分推迟到下节课检查，还算比较人性（课上检查老师会检查上板结果，读一读代码，讲一下怎么实现的）。

硬件描述语言和高级程序设计语言差别很大，很多时候你逻辑对了，但是不符合硬件实现，上板就会出错，也很难调试。就算调试仿真对了，上板不行还是不行的。一定要按照规范编写，不然会出现很多意想不到的错误。

第一节课关于相关操作要认真对待，熟练好。每次实验前尽量将自己的思路先整理清晰再开始写代码，避免不必要的错误。

课程实验有专门的网站，要求和语言语法知识都有，还是不错的。

建议用 vscode 编写 verilog，用过的都说好，vivado 的编辑器一言难尽。

最后一次实验难度超大，需要大量时间和精力，bug 只能自己解决，可能需要几个晚上的头发吧，但是输出正确结果时还是很高兴的。
"""
author = { name = "criwits", link = "https://github.com/criwits", date = "2022-06-01" }

[[lab]]
content = """时过境迁，2025 年的 AI 终于会写 verilog 了，这大大降低了实验的难度，不过还是要自己理解 AI 输出的内容，防止在检查环节被老师拷打。
"""
author = { name = "Cecilia", link = "https://github.com/mircecilia", date = "2026-01-01" }

[[advice]]
content = """不会完全按照课本进行讲授，每年讲授内容也不完全相同，学习请以当年 PPT 为准，教材仅供参考。"""
author = { name = "criwits", link = "https://github.com/criwits", date = "2022-06-01" }
