course_name = "离散数学"
repo_type = "normal"
course_code = "COMP2030"

# 授课教师 (Lecturers)
[[lecturers]]
name = "陈勇勇"

  [[lecturers.reviews]]
  content = """
  原本是教数理逻辑的老师，因此数理逻辑部分有些思路和这本教材不同，集合论图论部分节奏有些乱。
              口音较重，上课抑扬顿挫但是语速飞快，较难以跟上。
  """
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "任世军"

  [[lecturers.reviews]]
  content = """
  本部的资深老师，讲的很清晰，思路也很清楚。会提前发 PPT ，课堂上基本上以 PPT 作为纲要展开，有大量手写的推理。
              但是这门课非常抽象，所以很难学。听课应该还是有必要的，而且需要课后去总结发现一些规律。
              有问题可以直接私聊老师，老师很热情，很快回。助教好像只改作业。
  """
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "户保田"

  [[lecturers.reviews]]
  content = """
  据本人所说 2021 年春季他是首次负责这门课的授课工作。讲课很认真详细，对比较简单的内容也不会略过，会强调做题的书写过程。
              会花较多时间备课，对 PPT 上缺少的内容会提前补充，错误的内容会及时更正。对课堂问题、作业问题和考试纲要等的答疑很及时。
  """
  author = { name = "", link = "", date = "" }

# 教材与参考书(不需要author)
[[textbooks]]
title = "离散数学"
book_author = "屈婉玲 / 耿素云 / 张立昂"
publisher = "高等教育出版社"
edition = "第 2 版"
type = "textbook"

[[textbooks]]
title = "数理逻辑引论"
book_author = "李涛 / 张岩 / 刘峰"
publisher = "哈尔滨工业大学出版社"
edition = ""
type = "textbook"

[[textbooks]]
title = "Discrete Mathematics and Graph Theory -- A Concise Study Companion and Guide"
book_author = "K.Ericiyes"
publisher = ""
edition = ""
type = "reference"

[[exam]]
content = """
原《集合论与图论》部分：
考试比较简单，比上课老师讲的证明题简单很多。
题型有选择，填空，判断，大题，题目多是基础概念、公式的考查，以及 ppt 上的练习和作业题。
"""
author = { name = "", link = "", date = "" }

[[exam]]
content = """
原《数理逻辑》部分：
作为一门很纯正的数学类科目，基本上是「会者不难，难者不会」。不过捞人还是捞的。
考试的题目类型很固定，看几份卷子就能总结出来。全是大题，基本不存在死扣概念的题目，所以理解比背记重要得多。
老师在考前发布了 19 年试卷（这也是试卷资源的由来）。但是似乎不想发 20 年的。
网上还有残存的本部试卷，题型基本类似，可以一看。
"""
author = { name = "", link = "", date = "" }

[[exam]]
content = """
24 年秋季学期，考试对大定理证明、生成树数量求解、对偶图画图、中国邮路问题、最短路求解、推理定律证明和自然推理过程不要求，上课没涉及的电话系统设计和可消解问题也不要求，因此数理逻辑部分几乎仅剩下等值演算和一些基本概念。
考试重点仍然在图论部分（毕竟内容多学时多），证明题基本是课上例题和作业题的变种，做过类似的基本能照猫画虎证明个大概，出了好几题图论的实际应用难度不小。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-08-01" }

[[advice]]
content = """
作业一开始几次难度还可以接受；到中后期，难度挺大，建议参考习题解答指导书和 ppt 来完成。
个人建议，先把概念背熟——一个个字的背。然后对于定理证明，可能要慢慢地看，多参考 ppt 例题的方法，建立起集合论与图论的构造性思维。
复习时以 ppt 和作业为主，题目基本上是 ppt 和书本课后练习的原题。
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """
《集合论与图论》与《数理逻辑》合并后，重点仍然在集合论与图论部分。数理逻辑部分注意蕴涵式与现实理解不完全相同，理解文字描述和数学符号的转化即可。
集合论部分在高中函数与映射的基础上进一步抽象化，图论则是前两者的集大成，用数理逻辑的规则、集合论的语言描述图论问题，概念繁杂生涩，多加记忆，证明题基本上是初见杀，见过了可能也不会（
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-08-01" }

# 课程安排
[[schedule]]
content = """大体时间安排是 16 学时数理逻辑 + 16 学时集合论 + 32 学时图论，不同老师上课进度有所不同。"""

# 兜底板块
[[misc]]
topic = "教材说明"
content = """
第一本教材（屈婉玲版）为《集合论与图论》和本门课的教材，第二本教材（李涛版）为《数理逻辑》的教材。
请在使用往年资料时注意数理逻辑部分一些数学符号和语言表述的不同。
"""
author = { name = "", link = "", date = "" }
