course_name = "近世代数"
repo_type = "normal"
course_code = "COMP2010"

# 授课教师 (Lecturers)
[[lecturers]]
name = "唐琳琳"

  [[lecturers.reviews]]
  content = """很不错的老师，出题偏基础，但讲课很快。同时还是「集合论与图论」这门课的老师，出题风格可以参考。"""
  author = { name = "", link = "", date = "" }

# 教材与参考书(不需要author)
[[textbooks]]
title = "近世代数"
book_author = ""
publisher = "高等教育出版社"
edition = "第 3 版"
type = "textbook"

# 网络资源（电子书、网课等）
[[online_resources]]
title = "【直播回放】近世代数"
url = "https://www.bilibili.com/video/BV1GT4y1o7oc/"
description = "疫情时代的雨课堂视频回放，可用于复习。"

# 核心课程评价区块
[[course]]
content = """课程是很难的课程，涉及的概念都挺抽象的，但是过还是很容易的。"""
author = { name = "", link = "", date = "" }

[[exam]]
content = """
18、19 级考得很简单，作业能搞懂或者背下来就没问题了。
选择填空基本上是概念题，计算题也是很基础的，证明题在课上有暗示过可能会考，因此可以提前复习。
"""
author = { name = "", link = "", date = "" }

# 兜底板块
[[misc]]
topic = "作业说明"
content = """作业题都来自课本每一节后的习题，在 slide（网盘计划）中可见。"""
author = { name = "", link = "", date = "" }
