course_name = "微积分B"
repo_type = "normal"
course_code = "MATH1015B"

# 授课教师 (Lecturers)
[[lecturers]]
name = "余君武"

  [[lecturers.reviews]]
  content = """
  授课风格：
              - 板书为主，幻灯片为辅（更像他的讲义），首先板书细致讲本节课内容和重点，再念一遍 ppt，还会逐题板书讲幻灯片例题
              - 偶尔吹水，但内容也与课程有关，基本是以生动的例子来类比定理，给你直觉上的理解
              - 每章讲完后会上一节习题课，其中有相当一部分就是黄本原题
              - 讲课非常有活力，有时讲兴奋了还会「指指点点」，气氛拉满
              - 可能因为例题还没讲完而拖堂
            
              听课建议：
              - 老师上课时会补充不少 经典例题、方法、技巧 等，非常值得记下来；此外，他还会解释常见的 错误理解、难点 等，帮助你理解概念——这正是自学容易忽略的地方
              - （于 2024.4.15 更新）学到二重积分时，老师会开始考勤。当然这不是一件坏事——后面的东西，正如余老师、OpenAuto 的学长所言，难度很大，自学更是不一定学得懂
              - 可以参考本部的《工科数学分析学习指导与习题解答》，他的讲解和这本书有一些重合部分
            
              课后：
              - 所有上课的课件都会发群里（甚至可以直接提醒他发），也会时不时分享一些技巧、黄本题目答案之类
              - 不懂可以直接问，非常负责任
  """
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2024-03-01" }
[[lecturers]]
name = "严志彬"

  [[lecturers.reviews]]
  content = """
  授课风格：
              - 纯板书，板书风格比较潦草，随心而动。板书和课本并不完全一致（主要是顺序上的）。
            
              听课建议：
              - 建议听课，老师上课很有活力，而且逻辑特别清晰。
              - 由于严老师常年教学数学系，思维和工科数学的思维有很多的不同，偏重数学定理的证明。但是你认真听他的课一定会受益良多，在数学思维上有很大的提升。
              - 严老师的习题课并不局限于习题本身，而是跳出习题从更高的思维角度解读题目，对微积分的理解能让你超越课本的。
  """
  author = { name = "Gaster", link = "https://github.com/WDGaster", date = "2025-01-01" }
[[lecturers]]
name = "包革军"

  [[lecturers.reviews]]
  content = """  “当他在期末最后一节课上向到场的所有学生鞠躬致谢时，我便知道他是我在大一遇到的最有哈工大人气质的教授。”
  """
  author = { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "" }

  [[lecturers.reviews]]
  content = """
  授课风格：
              - 完全不用幻灯片，纯板书，而且板书非常有条理，把他的板书全部抄下来就是一份可读性很好的笔记了。
              - 偶尔会点名。有学生觉得他讲得太慢，但事实上这位老先生总能在最后一刻讲完所有要讲的东西。
              - 唯二的问题是板书时常出现笔误、总是拖堂。这两个问题出在这个老师身上我觉得都不是问题了，这并不影响他讲课的连贯性和逻辑性。如果出现笔误可以在课堂上尽早指出来，就不会耗费太多时间。
            
              听课建议：
              - 如果你愿意听他的课，最好就完全跟着他的思路来。老师会在课上讲很多的例题，如果能把它们都记下来并且课后稍微复习一下，基本上就足够掌握这一部分的内容了。
              - 如果你是挑剔的学生，大多数课都不愿意听老师讲，那么他的课应该是你最后一个选择skip的。
  """
  author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-18" }

# 教材与参考书(不需要author)
[[textbooks]]
title = "高等数学下册"
book_author = "同济大学数学系"
publisher = "高等教育出版社"
edition = "7版"
type = "textbook"

[[textbooks]]
title = "大学数学. 工科数学分析下册"
book_author = "哈尔滨工业大学数学学院"
publisher = "高等教育出版社"
edition = "6版"
type = "textbook"

[[textbooks]]
title = "工科数学分析学习指导与习题解答下册"
book_author = "哈尔滨工业大学数学系分析研究室"
publisher = "高等教育出版社"
edition = ""
type = "reference"

[[exam]]
content = """
考试难度：
- 半期考试比较容易，25+ 对于大多数同学是能实现的。
- 期末考试由于曲线曲面积分以及级数的加入，计算量陡增，难度也随之增加，想上 40 分会比较有挑战性，挂科率也是相当高。

2024春情况：
- 期末考试并没有特别难，曲面积分和级数的计算量相对于作业题都不大；可能是三个校区第一年统一考试，不想太为难学生？还是不要掉以轻心为好。
"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2024-07-01" }

[[advice]]
content = """
关于老师：
看了上面关于两位老师的评价我觉得特别合适，他们都是非常认真负责的老师，都是可以信赖可以跟着走完一整门课的老师。

学习衔接：
由于 微积分B 和 微积分A 的学习是一脉贯通的，因此可以移步 [微积分A](https://hoa.moe/docs/fresh-autumn/math1015a/) 仓库观看详细的学习指导。
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-18" }

[[advice]]
content = """作业按章提交，题量较多，但时间也比较充足，建议每上完一次课就按时复习并完成相应作业题，不要等到 ddl 再写，会来不及，而且及时写作业可以巩固当前刚学习的新知识。
"""
author = { name = "Wei HE", link = "https://github.com/hewei2001", date = "2020-01-01" }
