course_name = "机器人学基础"
repo_type = "normal"
course_code = "MECH3060"

# 授课教师 (Lecturers)
[[lecturers]]
name = "徐文福"

  [[lecturers.reviews]]
  content = """（待补充）"""
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "袁晗"

  [[lecturers.reviews]]
  content = """（待补充）"""
  author = { name = "", link = "", date = "" }
[[lecturers]]
name = "闫磊"

  [[lecturers.reviews]]
  content = """授课风格：讲课比较有活力，会结合自己的研究/业界近况讲解一些知识点的意义。没有考勤，但有若干（不算分？）的小测。"""
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-12-01" }

[[exam]]
content = """半开卷，最多可带一张 A4 纸。虽然作业的计算量非常大，但考试并不会有那么多数值计算，还是以参数形式推导居多。"""
author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-12-01" }
