course_name = "普通天文学"
repo_type = "normal"
course_code = "SPST1004"

# 授课教师 (Lecturers)
[[lecturers]]
name = "邹蓬"

  [[lecturers.reviews]]
  content = """邹老师的课其实挺有意思的，老师的思维发散，容易跳跃到别的地方。PPT 有些硬核，但是难懂的部分一般会跳过不讲，也不会考察。而重点部分会详细讲解。"""
  author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01-01" }
[[lecturers]]
name = "申远灯"

  [[lecturers.reviews]]
  content = """上课讲ppt的内容"""
  author = { name = "洛阳铲", link = "", date = "" }

# 核心课程评价区块
[[course]]
content = """
2024 秋课程考勤共四次，邹老师看心情考勤，每次 15 个人，抽到没到且下课仍未补签的算缺勤，缺勤一次扣 5 分，3 次扣 20 分且不再扣。
作业为助教所布置，基本都是简单的计算题，2024 秋的作业也在资料下载中可以看到，每次 6 分，共 5 次，作业和期末考的计算题强相关，而且难度不高。
课程为天文学的半科普半专业课程，上课会涉及很多很专业的名词和晦涩难懂的概念，也会有很多复杂无比的计算，但是这些都不重要！本门课程是通识课，只要求最基本的部分，如恒星研究中最广泛使用的赫罗图。
邹老师和助教张昶博士会带大家实地观测，地点位于 L8 的小平台。主要使用望远镜观测星空和太阳。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01-01" }

[[course]]
content = """
2025春课程考勤很少
共5次作业，与期末考计算题强相关
"""
author = { name = "洛阳铲", link = "", date = "" }

[[exam]]
content = """24 秋期末考试闭卷，可以使用计算器，题型为 10 题填空 + 5 题简答 + 2 题计算，具体可看资料中的回忆版试卷。填空题是天文学中最基础的知识，如八大行星；简答题是上课重点讲解的部分，如赫罗图；计算题和作业题内容差不多，主要是两部分：星等和距离的相关计算、开普勒三定律和牛顿运动定律在天体物理中的应用。"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01-01" }

[[exam]]
content = """25 春期末考试闭卷，可以使用计算器，题型为 20 题选择 + 10 题填空 + 5 题简答 + 4 题问答+ 2 题计算，计算题为作业原题，简答和问答仍然是上课重点讲授的内容，选填难度不高。"""
author = { name = "洛阳铲", link = "", date = "" }
