course_name = "电气专业选修课"
course_code = "EE30XX"

# 全局注意事项/简介
notices = """
电气专业的选修课开设于第三学年春季学期和第四学年秋季学期。

自 22 级起，电气专业的选修课不再区分“电力系统及其自动化”和“电力电子与电机驱动”两个方向，而是从全部课程中选择任意门修读满足学分要求即可。
- 22 级要求 9 学分
- 23 级要求 8 学分
- 24 级要求 10 学分
"""

# 成绩评定
[grade]
  [grade.default]
    default = "各选修课考核方式差异较大，具体请参考下方各课程板块说明。"

# 课程详细板块 (使用 misc 拆分不同选修课)

# --- 第三学年春季学期 ---

[[misc]]
topic = "EE3004 电气传动自动控制系统"
content = """
**授课教师**：詹瀚林
**学分**：2
**学时**：总学时 32 (理论 22 / 实验 10)
**成绩构成**：课程报告 70% + 实验 30%

讲电机控制相关的东西，FOC，SVPWM 等，然后还涉及很多很多自控方面的东西，难度在选修课程上也是挺难的了。电机控制方向的选修课，比较硬核或者是非常硬核。

课程实验类似电机学的实验，照着指导书做就好了。

课程报告老师是说自由发挥的，我做的是 FOC 的控制，还加了无感控制的一些东西，反正就是搭仿真写篇课程报告，其实还挺麻烦的。
"""
author = { name = "ZSA", link = "", date = "2025-11-01" }

[[misc]]
topic = "EE3011 开关电源原理与设计"
content = """
**授课教师**：朱荣伍
**学分**：2
**学时**：总学时 32 (理论 22 / 实验 10)
**成绩构成**：课堂表现 50% + 课程报告 50%

上课我听不懂在讲什么东西，相当于是电力电子技术这门课的延拓，会讲一些电力电子书里面王明彦老师没划重点的东西，想保研浙大电力电子的同学这门课建议选一下，然后认真搞懂里面的知识点，据说面试时会问到，而且问的比较细。

实验难度较大，每年实验内容会有变化，借鉴不了往届学长学姐的，只能自己做，而且实验老师是王丹丹老师，规格严格。
"""
author = { name = "LJH", link = "", date = "2025-11-01" }

[[misc]]
topic = "EE3011 开关电源原理与设计"
content = """
主要讲开关电源定义、原理、设计等内容，是电力电子技术的拓展，会详细讲 Buck 电路、正激电路、反激电路这类电路，开关管的控涉及比较多自动控制原理的内容。实际要学的话还是比较难的课，而且在选修的课程中选难度顶尖的，但是如果是要走电力电子方向还是可以好好学一下的。

课程报告直接将我们实验报告写成课程报告的形式，做的是 Buck 电路的仿真，网上可以搜到参考的资料，认真做还是做的出来的。
"""
author = { name = "ZSA", link = "", date = "2025-11-01" }

[[misc]]
topic = "EE3012 分布式电源与新能源发电"
content = """
**授课教师**：潘学伟
**学分**：2
**学时**：总学时 32 (理论 16 / 实验 16)
**成绩构成**：平时及实验 50% + 课程报告 50%

课程难度适中，学的东西是电力电子化的电力系统，主要是学新能源并网技术，和电力电子方向靠的也挺近。

实验难度适中，正常不用拖堂做，有硬件实验和 PSIM 仿真软件实验。
"""
author = { name = "LJH", link = "", date = "2025-11-01"