course_name = "文理通识"
course_code = "GeneralKnowledge"

notices = """
【关于文理通识】
文理通识课程是校区审批设置的面向全体本科生开设的全校区任选的自主发展课程。
文理通识学分不计入核心学分绩的计算，但是计入总学分绩的计算。

【修读限制】
自大一春季学期开始，每学期最多选择**三门**文理通识课程修读，其中 MOOC 课程不超过**两门**，不可以重复修读已修读的课程。

【选课方式】
1. 线下课：采用志愿式选课。志愿只是表征优先级，并非五个志愿只能抽中一个。如果第一志愿人数超过容量，第二志愿将无法录上。
2. MOOC：采用直选式选课。
注意：文理通识选课时间一般为开学初，和必修课以及跨专业课程都不相同。

【容量限制】
线下课程一般是小班教学（约 30 人），MOOC 课程容量充足（约 2000 人）。
"""

[grade]
[grade.default]
default = "文理通识学分不计入核心学分绩，但计入总学分绩。具体单科考核方式因课程而异，请参考下方具体课程评价。"

[[online_resources]]
title = "文理通识 MOOC 课程列表"
url = "https://hoa.moe/docs/general-knowledge/mooc/"
description = "MOOC 课程详细内容及列表"
author = { name = "HOA", link = "https://hoa.moe", date = "" }

[[online_resources]]
title = "文理通识线下课程文档"
url = "https://hoa.moe/docs/general-knowledge/"
description = "部分线下课程和相关资源"
author = { name = "HOA", link = "https://hoa.moe", date = "" }

[[lecturers]]
name = "刘波 (西方艺术大师及其作品鉴赏)"
  [[lecturers.reviews]]
  content = """
  刘波老师人非常好，上课偶尔以提问方式点名，考核方式是期中论文40%+期末论文40%+平时考勤20%。
  拿高分不太容易（本人得分95，要很认真写论文**体现出自己的思考**，属于比较少的现象），但基本交了论文就能过（我室友基本一节课没去，没被点到，也有80+）。
  """
  author = { name = "Oliver Wu", link = "", date = "" }

  [[lecturers.reviews]]
  content = """
  至今遇到的最好的文理通识老师，不过考勤略多，考勤方式是点名回答问题，频率大概是三节课轮回一次。
  老师对西方艺术很有心得，只要你对西方艺术有一点点兴趣，我都推荐选这个课，真的很建议听听，不过你在课上干别的事老师也会表示理解，从各种角度看都算的上绝世好课。
  """
  author = { name = "Cecilia", link = "", date = "" }

[[lecturers]]
name = "侯老师 (书法基础)"
  [[lecturers.reviews]]
  content = "比较好水的课，老师不错，期末作业是写一幅书法作品。"
  author = { name = "Ayn", link = "", date = "" }

  [[lecturers.reviews]]
  content = "没基础还不好意思请假的纯坐牢，老师教授的内容少，课上主要是练习（我 23 年上的，现在不知道什么样），分倒是好拿，看你自己了。"
  author = { name = "梦倾城终会醒", link = "", date = "2023-01-01" }

  [[lecturers.reviews]]
  content = """
  侯老师人很好，我是24年春季上的，一次课连上两节，老师先讲理论40分钟左右（我偶尔会太困睡着，老师不管的），剩余时间自由练习毛笔字，一次课结束前半小时把练习作品拍照发群里老师点评。
  期末考核是课程中期的一次ppt展示（主题是书法家介绍）+一份期末毛笔字作品，会给三节课左右的时间写期末作品，不占用课下时间，写得好还可以参加展览（我的就展在t4楼下）赚一分活动分（有参展证明）。
  期末给分也高，我拿了94分。有基础冲就完了，包你成为课上最靓的仔。
  """
  author = { name = "沐沐激推bot", link = "", date = "2024-03-01" }

[[lecturers]]
name = "吴丹 (声乐理论与实践)"
  [[lecturers.reviews]]
  content = "可以学，如果有一点乐理基础的话（能看懂简谱），上课体验会好很多；学发声技巧，日常发声训练和唱歌，期末展示是唱一首自己喜欢的歌（23年上）。"
  author = { name = "三水月可", link = "", date = "2023-01-01" }

  [[lecturers.reviews]]
  content = """
  我是23年秋季上的，吴丹老师人不错，但是对学生的演唱能力有一定要求，上课会轮流唱五线谱，0基础唱不出来的话可能会有点社死。
  期末考核是在学期内学过的所有五线谱和简谱歌曲片段中抽两首在全班面前演唱展示，想全部复习到位的话需要花点时间。
  不建议想水学分的人选，建议喜欢唱歌，五音全，且e的人选。这节课最好不要请假，我有演唱基础，期末唱的也不错，可能是因为请假太多老师给了88分，略低了。
  """
  author =