course_name = "体育"
course_code = "PE100X"

notices = """
- **学分情况**：
  - 大一两个学期：PE1001 是 1 学分 32 学时
  - 大二、大三四个学期：PE1002 是 0.5 学分 16 学时
- **选课指南**：关于选课可以参考 [HITSZ 新生手册/课内课程/体育课相关](https://hitsz.flowus.cn/hitsz/share/a471785a-4843-4ac3-8106-260776dc5355)。
- **免责声明**：以下体育课关于考核的部分，仅代表贡献者当时的情况，不能保证每年都一样。
- **大三体育政策 (2024起)**：
  1. 大二春季学期体测及格的同学，参加**健康跑** + 期末考试；
  2. 大二春季学期体测不及格的同学，参加**体育训练课** + 期末考试。
"""

[grade]
[grade.default]
default = "各专项考核标准不同，通常包含：考勤(10%) + 理论(10%) + 身体素质(30%) + 专项技术(50%)。具体请参考下方各专项说明。"

[[lecturers]]
name = "王明磊"
  [[lecturers.reviews]]
  content = """
  （体育基础）很好的老师，对于修读体育基础班的同学的身体水平有充分的认识，上课很摆。
  田径专业的体育老师，上课训练量都不大，只要你认真跟随老师的学习，一学期体测成绩就能飞速上升。如果你只是想修满体育学分，体育基础课也能轻松划水通过。
  """
  author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01-01" }

[[lecturers]]
name = "何嘉勇"
  [[lecturers.reviews]]
  content = """
  （体育基础）王明磊老师的师弟，24 春季学期时要求很高，到 24 秋季学期时和已经进化到师兄看齐。
  田径专业的体育老师，上课训练量都不大。
  """
  author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-01-01" }

[[lecturers]]
name = "钱星豪"
  [[lecturers.reviews]]
  content = """
  （体能训练）已离职。
  前半节针对七项身体素质进行训练（速度、柔韧性、耐力、爆发力、协调性、平衡性、力量），后半节课进行橄榄球/飞盘比赛。
  """
  author = { name = "IcyDesert", link = "https://github.com/IcyDesert", date = "2025-07-01" }

[[lecturers]]
name = "倪婧娇"
  [[lecturers.reviews]]
  content = """
  （游泳）非常好的老师，人美心善。
  零基础的同学只要跟着老师教的步骤照做，多练习几次就能学会，不要害怕呛水。
  课上会将同学们分为零基础和有基础两组，有基础的同学学习自由泳，零基础的同学学习蛙泳。
  """
  author = { name = "longlin10086", link = "https://github.com/longlin10086", date = "2024-03-01" }

[[lecturers]]
name = "曾翠兰 / 周紫微"
  [[lecturers.reviews]]
  content = """
  （跆拳道/空手道）好（各种方面的）。
  """
  author =