course_name = "计算机系统"
repo_type = "normal"
course_code = "COMP3052"

# 授课教师 (Lecturers)
[[lecturers]]
name = "（教师名）"

  [[lecturers.reviews]]
  content = """
  授课风格：
              听课建议：
              ……
  """
  author = { name = "", link = "", date = "" }

# 教材与参考书(不需要author)
[[textbooks]]
title = "Computer Systems: A Programmer’s Perspective"
book_author = ""
publisher = "Pearson"
edition = "Third Edition (2016)"
type = "textbook"

[[textbooks]]
title = "计算机系统基础"
book_author = "袁春风"
publisher = "南京大学"
edition = ""
type = "textbook"

# 网络资源（电子书、网课等）
[[online_resources]]
title = "课程 Web 网站 (CMU)"
url = "http://www.cs.cmu.edu/~213"
description = "CMU完整的课程资料,包括PPT、实验、课外阅读、视频等"

[[online_resources]]
title = "原版英文 PPT"
url = "https://www.cs.cmu.edu/afs/cs/academic/class/15213-s15/www/schedule.html"
description = "下载地址"

[[online_resources]]
title = "CSAPP 课程视频 (CMU)"
url = "https://www.bilibili.com/video/BV1iW411d7hd/?spm_id_from=333.999.0.0&vd_source=9b3ebd8f0d9db179d1b637e52d4b1303"
description = "B站搬运"

[[online_resources]]
title = "CSAPP 课程视频 (九曲阑干)"
url = "https://www.bilibili.com/video/BV1cD4y1D7uR/?spm_id_from=333.999.0.0&vd_source=9b3ebd8f0d9db179d1b637e52d4b1303"
description = "许多学长推荐"

[[online_resources]]
title = "计算机系统课程视频 (北航)"
url = "https://www.bilibili.com/video/BV19X4y1P7zW/?spm_id_from=333.999.0.0&vd_source=9b3ebd8f0d9db179d1b637e52d4b1303"
description = "B站搬运"

[[online_resources]]
title = "计算机系统基础(一)：程序的表示、转换与链接"
url = "https://www.icourse163.org/course/NJU-1001625001?from=searchPage&outVendor=zw_mooc_pcssjg_"
description = "南京大学（袁春风）MOOC"

[[online_resources]]
title = "计算机系统基础（二）：程序的执行和存储访问"
url = "https://www.icourse163.org/course/NJU-1001964032?from=searchPage&outVendor=zw_mooc_pcssjg_"
description = "南京大学（袁春风）MOOC"

[[online_resources]]
title = "计算机系统基础(三)：异常、中断和输入/输出"
url = "https://www.icourse163.org/course/NJU-1002532004?from=searchPage&outVendor=zw_mooc_pcssjg_"
description = "南京大学（袁春风）MOOC"

[[online_resources]]
title = "计算机系统基础（四）：编程与调试实践"
url = "https://www.icourse163.org/course/NJU-1449521162?from=searchPage&outVendor=zw_mooc_pcssjg_"
description = "南京大学（袁春风）MOOC"

[[online_resources]]
title = "计算机系统基础（五）：x86模拟器编程实践"
url = "https://www.icourse163.org/course/NJU-1464941173?from=searchPage&outVendor=zw_mooc_pcssjg_"
description = "南京大学（袁春风）MOOC"

[[online_resources]]
title = "2020 南京大学计算机系统基础习题课"
url = "https://www.bilibili.com/video/BV1qa4y1j7xk?p=7&vd_source=9b3ebd8f0d9db179d1b637e52d4b1303"
description = "B站搬运"

[[advice]]
content = """以下几个网课推荐来自老师的教学PPT，许多学长推荐学习九曲阑干的网课。"""
author = { name = "", link = "", date = "" }
