course_name = "服务计算"
repo_type = "normal"
course_code = "COMP3017"

# 授课教师 (Lecturers)
[[lecturers]]
name = "Joanna Siebert"

# 网络资源（电子书、网课等）
[[online_resources]]
title = "2023年春笔记"
url = "https://github.com/xuanhao44/Service-Computing"
description = "Service-Computing 课程笔记"

[[exam]]
content = """
形式：
- Open book 开卷
- Multiple choice questions – 10 questions, 3 points each 单选题！
- Short description questions – 5 questions, 6 points each
- Case questions – 40 points in total
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """参考书籍：有，但不需要读；全靠 PPT 就够了。"""
author = { name = "", link = "", date = "" }
