course_name = "软件构造实践"
repo_type = "normal"
course_code = "COMP3060"

[[exam]]
content = """会有选题中期和最后的答辩，尽量在每次答辩之前完成相应任务并给出成果。"""
author = { name = "", link = "", date = "" }

[[lab]]
content = """同学们在此次课程中可自由组队（1-3人）自由选题做一个工程（小程序、网站也可）。
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """
1. 建议提前规划好每周定时验收，不要把工作量全部压到最后。
2. 小组内工作量尽量均匀分配，有问题可随时向助教求助，此课程的助教经验很丰富，解答也非常耐心。
3. 结题报告内容较多，建议留足充足时间认真完成。
"""
author = { name = "", link = "", date = "" }
