course_name = "DSP的原理与应用"
repo_type = "normal"
course_code = "EE3005"

# 授课教师 (Lecturers)
[[lecturers]]
name = "叶剑"

  [[lecturers.reviews]]
  content = """
  授课风格：摆，念ppt，还是用催眠的语速。
            DSP在电机控制等方面应用其实很多，但是yj教的就是一坨，也没有什么网课资料，实验课学不到什么，上课点名你还不能跑，就纯纯无语
            实验课报告没有明确格式，但是最后实验分都给的很低（怀疑压分），有单片机基础的同学实验课相对没有那么坐牢
  """
  author = { name = "电气同学（这门课是他们的必修课）", link = "", date = "" }
[[lecturers]]
name = "王宏"

  [[lecturers.reviews]]
  content = """
  授课风格：懂得多，思维发散，但是有效信息密度低
            23 级之后，本门课程改为王宏授课，电气同学想必对他并不陌生（
  """
  author = { name = "", link = "", date = "" }

# 教材与参考书(不需要author)
[[textbooks]]
title = "TMS320F28335 DSP原理、开发及应用"
book_author = "符晓 / 朱洪顺"
publisher = "清华大学出版社, 2017"
edition = ""
type = "textbook"

# 网络资源（电子书、网课等）
[[online_resources]]
title = "SSC的DSP仓库"
url = "https://github.com/SSC202/DSP"
description = ""

[[exam]]
content = """考试背 ppt +自求多福"""
author = { name = "电气同学（这门课是他们的必修课）", link = "", date = "" }

[[exam]]
content = """考试基本上是F28335手册内容，全都是F28335概念题，甚至没讲的也会考。"""
author = { name = "SSC", link = "https://github.com/SSC202", date = "2024-11-01" }

[[advice]]
content = """
建议去学stm32原理，一定程度上可以类比
建议想学知识的自动化的同学别选
"""
author = { name = "", link = "", date = "" }

[[advice]]
content = """DSP是电力电子软件方向非常重要的课程，基本上电力电子方向的企业都在用DSP，课却上成这样确实不知道作何评论。建议自己在网上找一份F28335的课程自学。"""
author = { name = "SSC", link = "https://github.com/SSC202", date = "2024-11-01" }
